#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Audit des modes vs pairs_database."""
import re
from pairs_database import PAIRS
from collections import Counter

modes = Counter(p.get('mode','?') for p in PAIRS)
print('=== MODE COUNTS ===')
for m,c in sorted(modes.items()):
    print(f'  {m}: {c}')

# Heuristics per mode: set of allowed universe keywords (lowercased)
GAME_UNIVERSES = {
    'mario','zelda','pokemon','pokémon','sonic','final fantasy','god of war',
    'last of us','witcher','overwatch','street fighter','mortal kombat',
    'halo','metal gear','resident evil','tomb raider','red dead','gta','grand theft',
    'minecraft','undertale','kirby','mega man','doom','half-life',
    'portal','assassin','nier','bayonetta','horizon','uncharted',
    'crash bandicoot','splinter cell','hitman','devil may cry','donkey kong','metroid',
    'dragon quest','persona','fortnite','cyberpunk','elden ring',
    'dark souls','bloodborne','super smash','tekken','animal crossing',
    'pac-man','the sims','skyrim','elder scrolls','fallout','borderlands','bioshock',
    'apex legends','valorant','counter-strike','among us','fall guys',
    'castlevania','silent hill','dead space','monster hunter','kingdom hearts',
    'starcraft','warcraft','diablo','league of legends','team fortress',
    'soul calibur','injustice','killzone','gears of war','destiny',
    'dishonored','watch dogs','far cry','rayman','okami','yakuza',
    'hollow knight','celeste','hades','cuphead','stardew','terraria',
    'roblox','genshin','honkai','chrono','xenoblade','fire emblem',
    'paper mario','splatoon','pikmin','f-zero','mario kart','forza','gran turismo',
    'need for speed','rocket league','max payne','mafia','saints row',
    'ratchet','jak and daxter','spyro','sackboy','parappa','ape escape',
    'siphon filter','deus ex','thief','call of duty','battlefield',
    'life is strange','bioshock','control','returnal','death stranding',
    "ori and",'hollow knight','dead cells','little nightmares','inside','limbo',
    'journey','shadow of the colossus','ico','bloodborne','sekiro',
    "jeu vidéo","jeux vidéo","video game",'pong','galaga','space invaders',
    'tetris','punch-out','duck hunt','ice climber','contra','bomberman',
    'earthbound','mother','advance wars','luigi','wario','yoshi',
    'overcooked','peggle','plants vs zombies','angry birds','candy crush',
    "assassin's creed",'prince of persia','tomb raider','uncharted',
    'nintendo','sega','playstation','xbox','atari','arcade',
    "kena",'ghost of tsushima','spider-man','marvel rivals','mk','mortal',
    'balatro','fez','braid','bastion','transistor','pyre',
    'vampire survivors','among us','scott pilgrim','streets of rage',
    'wii sports','wii fit','mii','smash bros',
}

DISNEY_UNIVERSES = {
    'disney','pixar','marvel','star wars','lucasfilm','mickey','donald','goofy',
    'lion king','roi lion','aladdin','mulan','frozen','reine des neiges',
    'moana','vaiana','tangled','raiponce','rapunzel','cendrillon','cinderella',
    'belle','snow white','blanche-neige','peter pan','hercule','hercules',
    'tarzan','pocahontas','ariel','sirène','little mermaid',
    'toy story','nemo','monstre','monsters','ratatouille','incredibles','indestructibles',
    'wall-e','walle','up','là-haut','coco','soul','luca','turning red','alerte rouge',
    'encanto','brave','rebelle','ratatouille','bug','cars',
    'avengers','iron man','captain america','thor','hulk','spider-man','spiderman',
    'black widow','black panther','doctor strange','guardians','galaxy','wanda',
    'loki','deadpool','wolverine','x-men','fantastic four','daredevil',
    'punisher','ant-man','hawkeye','vision','scarlet witch','yelena',
    'jedi','sith','skywalker','vader','yoda','kenobi','mandalorian','grogu',
    'han solo','leia','palpatine','rey','finn','poe','kylo','ahsoka','din djarin',
    'boba fett','jango','clone','stormtrooper',
    'indiana jones','jones',
    'hannah montana','high school musical','zack','cody','wizards of waverly',
    'kim possible','phineas','ferb','gravity falls','ducktales','darkwing',
    'tron',"pirates of the caribbean","pirates des caraïbes",'jack sparrow',
    'national treasure',
    'cruella','maléfique','maleficent',
    'mickey mouse','minnie','daisy','scrooge',
    "alice in wonderland","alice au pays",
    'tinkerbell','fée clochette','winnie','pooh','bambi','dumbo',
    'simba','mufasa','scar','timon','pumbaa','nala',
    'woody','buzz','sulley','mike','boo','remy','linguini','incroyables','parr',
    'anna','elsa','olaf','sven','kristoff','hans',
    'rapunzel','flynn','maximus','pascal','eugene',
    'hercules','megara','hades','meg',
    'aladdin','jasmine','genie','jafar','abu','iago',
    'mulan','shang','mushu','shan yu',
    'pocahontas','john smith',
    'belle','beast','bête','gaston','lumière','cogsworth','chip','mrs potts',
    'merida','rebelle',
    'miguel','hector','coco',
    'joy','sadness','anger','fear','disgust','riley','bing bong',
    'nick wilde','judy hopps','zootopia','zootopie',
    'wreck-it ralph','ralph','vanellope',
    "wall·e",'eve','wall-e',
    'carl','russell','kevin',"là-haut",
    'moana','maui',
    'luisa','mirabel','bruno','isabela','camilo','dolores',
    'ian','barley','onward',
    'ember','wade','elemental',
    'dash','violet','jack-jack','helen','bob parr',
    'chihiro','haku','no-face',  # these are ghibli, not disney - exclude later
}

SERIES_TV_UNIVERSES = {
    'breaking bad','better call saul','game of thrones','got','house of the dragon',
    'stranger things','lupin','money heist','casa de papel','la casa de papel',
    'narcos','peaky blinders','the walking dead','walking dead','lost','friends',
    'the office','office','parks and recreation','seinfeld','community',
    'how i met your mother','himym','big bang theory','brooklyn nine-nine',
    'sherlock','true detective','fargo','better call','westworld','house md','dr house',
    'the witcher','black mirror','mindhunter','ozark','succession','the mandalorian',
    'dexter','prison break','24','homeland','band of brothers','chernobyl',
    'euphoria','the last of us','wednesday','mercredi','bridgerton','the crown',
    'dark','sense8','the boys','invincible','umbrella academy','cobra kai',
    'the umbrella','severance','ted lasso','only murders','white lotus','yellowjackets',
    "squid game",'squid','one piece live','avatar','one punch','arcane',
    'cuckoo',"the americans","handmaid","love death robots",
    "saul","vikings","spartacus","rome","boardwalk","sopranos","oz",
    "new girl","modern family","archer","it crowd","miranda","blackadder",
    "inbetweeners","peep show","fleabag","killing eve","line of duty",
    "bodyguard","outlander","downton","mad men","masters of","x-files","buffy",
    "angel","charmed","supernatural","fringe","flashforward","heroes","alias",
    "24",'arrow','flash','smallville','gotham','daredevil','jessica jones',
    "doctor who","torchwood","broadchurch","merlin","atypical",
    "punisher","iron fist","luke cage","agents of shield",
    "strictly","star trek","deep space nine","voyager","next generation",
    "picard","discovery","battlestar","stargate","farscape","firefly","serenity",
    "lupin","kaamelott","bref","validé","dix pour cent","engrenages","spiral",
    'élite','élite','élite','élite','elite','la mesías','la casa','paquita',
    'la noche','hit','sky rojo','casa','machos','valeria','fisica o quimica',
    'emily in paris','chef','the morning show','severance','see','pachinko',
    'reacher','jack ryan','tom clancy','bosch','mr robot','billions','industry',
    'you','how to get away','scandal','greys','grey','chicago med','chicago fire',
    'ncis','law and order','csi','criminal minds','blacklist','scorpion','suits',
    'the good doctor','this is us','dallas','knots landing','santa barbara',
    'will and grace','frasier','cheers','everybody loves','roseanne',
    'fresh prince','family matters','full house','charmed','sabrina',
    'gossip girl','90210','one tree hill','dawson',
    'vampire diaries','the originals','legacies','shadowhunters','the witcher',
    'lucifer','the boys','the 100','riverdale','sabrina','chilling',
    "walter white","jesse pinkman","saul goodman","gus fring","mike ehrmantraut",
    "skyler white","hank schrader","tuco",
    "jon snow","daenerys","tyrion","cersei","jaime","arya","sansa","bran","rob stark",
    "ned stark","eddard","khal drogo","sandor","gregor","littlefinger","varys",
    "eleven","mike","dustin","lucas","will byers","max","steve","nancy","jonathan",
    "hopper","joyce","demogorgon","vecna","billy",
    "thomas shelby","arthur shelby","john shelby","polly","alfie solomons",
    "assane diop","lupin","ben","guy de cornac",
    "professor","tokyo","rio","berlin","helsinki","nairobi","denver","moscow",
    "hannibal","will graham","jack crawford","bedelia","mason verger",
    "rust cohle","marty hart","true detective",
    "don draper","peggy olson","roger sterling","joan holloway","pete campbell",
    "jack bauer","kim bauer","tony almeida","chloe o'brian",
    "dexter morgan","debra morgan","rita","lundy","quinn","masuka","miguel prado",
    "rick grimes","michonne","daryl dixon","negan","carl grimes","glenn","maggie",
    "sherlock holmes","john watson","moriarty","mycroft","irene adler",
    "sheldon cooper","leonard hofstadter","howard wolowitz","raj koothrappali","penny",
    "bernadette","amy farrah fowler",
    "walter jr","ted mosby","marshall","lily","barney stinson","robin scherbatsky",
    "michael scott","jim halpert","pam beesly","dwight schrute","andy bernard",
    "kevin malone","oscar","creed","stanley","angela","phyllis","toby","ryan",
    "leslie knope","ron swanson","april ludgate","andy dwyer","ben wyatt",
    "tom haverford","ann perkins","jerry","chris traeger",
    "jake peralta","amy santiago","rosa diaz","terry jeffords","raymond holt",
    "charles boyle","gina linetti","hitchcock","scully",
    "kramer","george costanza","elaine benes","newman",
    "ross geller","rachel green","monica geller","chandler bing","joey tribbiani",
    "phoebe buffay",
    "tyrion lannister","cersei lannister","tywin lannister","jaime lannister",
    "yellowjackets",
    "lorelai gilmore","rory","luke danes","emily gilmore",
    "lucky luciano","meyer lansky","bugsy","al capone","gomorrah",
    "walter jr","marie schrader",
    "frodo","gandalf","aragorn","legolas","gimli","sam",
    # "Lord of the rings" is movie. Include rings of power?
    "galadriel","elrond","arwen","eowyn","sauron","saruman",
    "jack shephard","kate austen","james ford","sawyer","hurley","john locke",
    "jack","ben linus","desmond","charlie pace","claire littleton","sayid",
    "chuck","sarah","chuck bartowski","casey","morgan","ellie","awesome","general",
    "chuck bass","blair waldorf","serena","nate","dan humphrey","jenny",
    "tony soprano","carmela","christopher","paulie","silvio","uncle junior",
    "tim riggins","coach taylor","matt saracen","jason street","tyra",
    "michael bluth","gob","buster","lindsay","tobias",
    "charlie harper","alan harper","jake harper","berta","rose",
    "deacon","rayna",
    "harvey specter","mike ross","louis litt","donna","jessica pearson","rachel zane",
    "frank underwood","claire underwood","doug stamper",
    "detective","walter","jesse",
    "crazy","miranda","carrie bradshaw","samantha jones","charlotte","big",
    "jack","liz lemon","kenneth","tracy jordan","jenna maroney",
    "sarah connor","john connor","kyle reese","cameron","catherine",
    "will smith","fresh prince","uncle phil","carlton",
    "zack morris","kelly","slater","jessie","screech","lisa",
    "kenan","kel","good burger","saved by",
    "malcolm","reese","dewey","hal","lois","francis",
    "james dillon",
    "queen","charlotte","viscount","bridgerton",
    "ted lasso","rebecca welton","roy kent","keeley","jamie tartt","nate",
    "nine-nine","fleabag","claire","harry bosch","jack reacher",
}

CARTOON_UNIVERSES = {
    'simpson','homer','bart','lisa','marge','maggie','futurama','family guy',
    'peter griffin','stewie','brian','american dad','cleveland show','bob\'s burger',
    'south park','spongebob','bob l\'éponge','patrick','squidward','sandy','krabs',
    'plankton','mr krabs','gary',
    'tom and jerry','tom et jerry','looney tunes','bugs bunny','daffy duck','tweety',
    'sylvester','roadrunner','coyote','wile','porky','yosemite','marvin',
    'mickey','donald','popeye','scooby-doo','fred','daphne','velma','shaggy','scooby',
    'flintstone','pierrafeu','jetson','rugrats','hey arnold','doug','recess',
    'dexter','powerpuff','blossom','bubbles','buttercup','johnny bravo',
    'cow and chicken','courage','edd','ed eddy','eddy',
    'spongebob','fairly','jimmy neutron','danny phantom','avatar last',
    'aang','katara','sokka','zuko','azula','iroh','toph','appa','momo',
    'korra','asami','bolin','mako','tenzin','amon','kuvira',
    'adventure time','finn','jake','ice king','marceline','bubblegum','gunther',
    'regular show','mordecai','rigby','benson','pops','skips',
    'gumball','darwin','anais','banana joe',
    'steven universe','garnet','amethyst','pearl','lapis','peridot','ruby','sapphire',
    'rick and morty','rick sanchez','morty smith','summer','beth','jerry',
    'gravity falls','dipper','mabel','stan','ford','soos','wendy','bill cipher',
    'the owl house','luz','eda','king','amity','hunter','willow','gus','collector',
    'duck tales','darkwing','goof troop','tailspin','rescue rangers','chip','dale',
    'arthur','caillou','franklin','bob l\'éponge','jimmy two','camp lazlo',
    'total drama','6teen','stoked','fish hooks','pair of kings',
    'codename kids next door','foster\'s home','billy and mandy','grim',
    'chowder','flapjack','clarence','uncle grandpa','secret mountain',
    'we bare bears','craig of the creek','summer camp island','infinity train',
    'big city greens','duck tales','loud house','casagrandes','oggy',
    'garfield','heathcliff','alvin','chipmunks','smurfs','schtroumpfs',
    'he-man','she-ra','skeletor','master of the universe','thundercat',
    'x-men','spider-man','batman','superman','teen titan','robin','cyborg','starfire',
    'raven','beast boy','batgirl','nightwing','flash','green lantern',
    'transformer','optimus','megatron','bumblebee','autobot','decepticon',
    'gi joe','g.i. joe',
    'kim possible','ron stoppable','rufus','shego','drakken',
    'lilo stitch','stitch','lilo','jumba','pleakley',
    'beavis','butt-head','daria','aqua teen','sealab','venture',
    'rocko','hey arnold','cat dog','catdog','angry beavers','ren stimpy',
    'paw patrol','bluey','peppa pig','dora','diego','go diego',
    'sesame street','big bird','elmo','cookie monster','bert','ernie',
    'muppets','kermit','miss piggy','fozzie','gonzo','animal',
    'wallace gromit','shaun the sheep','chicken run','pingu','moomin',
    'oggy','pat et stan','pat stan','titeuf','lanfeust',
    'wakfu','ankama','code lyoko','lyoko','odd','yumi','ulrich','jérémie',
    'once upon a time...','il était une fois','inspecteur gadget',
    'iznogoud','astérix','obélix','idéfix','lucky luke','tintin','milou',
    'haddock','tournesol','dupond','dupont','gaston','spirou','fantasio',
    'schtroumpf','smurf',
}

CASUAL_UNIVERSES = {
    'métier','job','métiers','école','famille','couple','animal','sport',
    'nourriture','food','cuisine','musique','film','livre','voyage','nature',
    'technologie','histoire','politique','célébrité','celebrity','chanteur',
    'acteur','acteur','président','sportif','footballeur','boxeur','basketball',
    'tennis','rugby','formule 1','f1','nba','fifa','voleur','policier','pompier',
    'docteur','infirmière','professeur','avocat','juge','chef','cuisinier',
    'boulanger','pâtissier','artisan','mécanicien','coiffeur','fleuriste',
    'jardinier','pêcheur','marin','pilote','astronaute','explorateur',
    'inventeur','scientifique','philosophe','peintre','sculpteur','musicien',
    'compositeur','écrivain','poète','journaliste','présentateur','animateur',
    'chocolat','pizza','burger','sushi','pasta','kebab','taco','curry',
    'café','thé','vin','bière','whisky','cognac',
    'hockey','rugby','golf','tennis','badminton','ping-pong','squash','cricket',
    'natation','athlétisme','course','cyclisme','ski','snowboard','surf',
    'plage','montagne','forêt','désert','océan','lac','rivière','île','volcan',
    'ville','campagne','village','banlieue','capitale','quartier',
    'voiture','moto','vélo','bus','train','avion','bateau','camion',
    'maison','appartement','château','cabane','igloo','hôtel','restaurant',
    'lion','tigre','éléphant','girafe','ours','loup','renard','lapin','chat','chien',
    'cheval','vache','mouton','poule','cochon','canard','oiseau','poisson',
    'requin','dauphin','baleine','serpent','araignée','abeille','papillon',
    'fourmi','mouche','moustique','crocodile','dinosaure',
    # Super casual cultural
    'einstein','newton','tesla','edison','mozart','beethoven','bach','chopin',
    'picasso','van gogh','michel-ange','leonardo','dali','monet','renoir',
    'shakespeare','molière','hugo','zola','balzac','dumas','voltaire',
    'napoleon','césar','alexandre','cléopâtre','louis xiv','gandhi','mandela',
    'churchill','de gaulle','obama','lincoln','kennedy',
    'michael jackson','madonna','elvis','beatles','rolling stones','queen',
    'david bowie','prince','freddie mercury','johnny hallyday','aznavour',
    'ronaldo','messi','pelé','maradona','zidane','mbappé','neymar','beckham',
    'jordan','lebron','kobe','shaq','ali','tyson','mayweather','pacquiao',
    'mr.','madame','monsieur','président','roi','reine','prince','princesse',
    'pape','empereur','sultan','chevalier','samouraï','ninja','pirate','cowboy',
    'indien','viking','gladiateur','soldat','général','amiral','capitaine',
    # Abstract concepts
    'amour','amitié','famille','travail','argent','bonheur','tristesse',
    'colère','joie','peur','surprise','dégoût','espoir','rêve','cauchemar',
    'lundi','mardi','mercredi','jeudi','vendredi','samedi','dimanche',
    'janvier','février','mars','avril','mai','juin','juillet','août',
    'septembre','octobre','novembre','décembre',
    'printemps','été','automne','hiver',
    'matin','midi','soir','nuit','aube','crépuscule',
    'rouge','bleu','vert','jaune','violet','orange','rose','noir','blanc','gris',
    'rond','carré','triangle','rectangle','losange','ovale',
    'grand','petit','gros','maigre','beau','moche','jeune','vieux','riche','pauvre',
    'banque','hôpital','école','université','bibliothèque','musée','église','temple',
    'mosquée','synagogue','cimetière','parc','jardin','zoo','aquarium','cirque',
    'théâtre','cinéma','concert','opéra','musée','galerie',
    'ordinateur','smartphone','tablette','télévision','radio','caméra','appareil',
    'livre','journal','magazine','lettre','email','message','texto',
    'été','hiver','pluie','neige','soleil','nuage','vent','tempête','orage',
    'manger','boire','dormir','travailler','jouer','lire','écrire','dessiner',
    'courir','marcher','sauter','nager','voler','conduire','cuisiner','chanter',
    'danser','rire','pleurer','parler','crier','chuchoter','siffler',
    # Personal life
    'mariage','anniversaire','naissance','vacances','retraite','divorce','déménagement',
    'rendez-vous','réunion','entretien','examen','diplôme','stage','interview',
    'boulanger','barbier','coiffeur',
    # Generic characters used for Casual mode
    'papa','maman','frère','sœur','enfant','bébé','grand-père','grand-mère',
    'oncle','tante','cousin','cousine','ami','amie','voisin','voisine','collègue',
    'patron','employé','client','vendeur','acheteur','touriste','étranger',
    # People / life archetypes - casual
    'casual','grand public','quotidien','générique',
}


def contains_any(text, keywords):
    tl = text.lower()
    return any(k in tl for k in keywords)


def audit_mode(mode, keywords, label):
    pairs = [p for p in PAIRS if p.get('mode') == mode]
    suspects = []
    for p in pairs:
        u1, u2 = p.get('universe1',''), p.get('universe2','')
        c1, c2 = p.get('civil',''), p.get('undercover','')
        t1 = u1 + ' ' + c1
        t2 = u2 + ' ' + c2
        ok1 = contains_any(t1, keywords)
        ok2 = contains_any(t2, keywords)
        if not ok1 or not ok2:
            suspects.append(p)
            print(f'SUSPECT {label}: {c1} ({u1}) / {c2} ({u2})')
    print(f'  Total {label} suspects: {len(suspects)}/{len(pairs)}')
    return suspects


print('\n=== AUDIT jeux_video ===')
audit_mode('jeux_video', GAME_UNIVERSES, 'jv')
print('\n=== AUDIT disney ===')
audit_mode('disney', DISNEY_UNIVERSES, 'disney')
print('\n=== AUDIT series_tv ===')
audit_mode('series_tv', SERIES_TV_UNIVERSES, 'series_tv')
print('\n=== AUDIT cartoons ===')
audit_mode('cartoons', CARTOON_UNIVERSES, 'cartoons')
