"""
Comprehensive manga/anime character pairs database for Undercover game.
160+ pairs with real thematic/narrative similarities.
"""

PAIRS = [
    # =========================================================================
    # CROSS-UNIVERSE PAIRS
    # =========================================================================

    # -------------------------------------------------------------------------
    # SENSEI PROTECTEUR (10+)
    # -------------------------------------------------------------------------
    {
        "civil": "Kakashi Hatake",
        "undercover": "Gojo Satoru",
        "universe1": "Naruto",
        "universe2": "Jujutsu Kaisen",
        "archetype": "Sensei Protecteur",
        "wiki1": "naruto",
        "page1": "Kakashi Hatake",
        "wiki2": "jujutsu-kaisen",
        "page2": "Satoru Gojo",
    },
    {
        "civil": "Iroh",
        "undercover": "Barbe Blanche",
        "universe1": "Avatar",
        "universe2": "One Piece",
        "archetype": "Sensei Protecteur",
        "wiki1": "avatar",
        "page1": "Iroh",
        "wiki2": "onepiece",
        "page2": "Edward Newgate",
    },
    {
        "civil": "Jiraiya",
        "undercover": "Shanks",
        "universe1": "Naruto",
        "universe2": "One Piece",
        "archetype": "Sensei Protecteur",
        "wiki1": "naruto",
        "page1": "Jiraiya",
        "wiki2": "onepiece",
        "page2": "Shanks",
    },
    {
        "civil": "All Might",
        "undercover": "Gojo Satoru",
        "universe1": "My Hero Academia",
        "universe2": "Jujutsu Kaisen",
        "archetype": "Sensei Protecteur",
        "wiki1": "myheroacademia",
        "page1": "Toshinori Yagi",
        "wiki2": "jujutsu-kaisen",
        "page2": "Satoru Gojo",
    },
    {
        "civil": "Biscuit Krueger",
        "undercover": "Genkai",
        "universe1": "Hunter x Hunter",
        "universe2": "Yu Yu Hakusho",
        "archetype": "Sensei Protecteur",
        "wiki1": "hunterxhunter",
        "page1": "Biscuit Krueger",
        "wiki2": "yuyuhakusho",
        "page2": "Genkai",
    },
    {
        "civil": "Urahara Kisuke",
        "undercover": "Kakashi Hatake",
        "universe1": "Bleach",
        "universe2": "Naruto",
        "archetype": "Sensei Protecteur",
        "wiki1": "bleach",
        "page1": "Kisuke Urahara",
        "wiki2": "naruto",
        "page2": "Kakashi Hatake",
    },
    {
        "civil": "Rayleigh",
        "undercover": "Jiraiya",
        "universe1": "One Piece",
        "universe2": "Naruto",
        "archetype": "Sensei Protecteur",
        "wiki1": "onepiece",
        "page1": "Silvers Rayleigh",
        "wiki2": "naruto",
        "page2": "Jiraiya",
    },
    {
        "civil": "Muten Roshi",
        "undercover": "Jiraiya",
        "universe1": "Dragon Ball",
        "universe2": "Naruto",
        "archetype": "Sensei Protecteur",
        "wiki1": "dragonball",
        "page1": "Master Roshi",
        "wiki2": "naruto",
        "page2": "Jiraiya",
    },
    {
        "civil": "Piccolo",
        "undercover": "Kakashi Hatake",
        "universe1": "Dragon Ball",
        "universe2": "Naruto",
        "archetype": "Sensei Protecteur",
        "wiki1": "dragonball",
        "page1": "Piccolo",
        "wiki2": "naruto",
        "page2": "Kakashi Hatake",
    },
    {
        "civil": "Shanks",
        "undercover": "Gildarts Clive",
        "universe1": "One Piece",
        "universe2": "Fairy Tail",
        "archetype": "Sensei Protecteur",
        "wiki1": "onepiece",
        "page1": "Shanks",
        "wiki2": "fairytail",
        "page2": "Gildarts Clive",
    },
    {
        "civil": "Koro-sensei",
        "undercover": "Urahara Kisuke",
        "universe1": "Assassination Classroom",
        "universe2": "Bleach",
        "archetype": "Sensei Protecteur",
        "wiki1": "ansatsukyoshitsu",
        "page1": "Korosensei",
        "wiki2": "bleach",
        "page2": "Kisuke Urahara",
    },

    # -------------------------------------------------------------------------
    # GENIE MAUDIT / ENFANT PRODIGE (10+)
    # -------------------------------------------------------------------------
    {
        "civil": "Killua Zoldyck",
        "undercover": "Sasuke Uchiha",
        "universe1": "Hunter x Hunter",
        "universe2": "Naruto",
        "archetype": "Génie Maudit",
        "wiki1": "hunterxhunter",
        "page1": "Killua Zoldyck",
        "wiki2": "naruto",
        "page2": "Sasuke Uchiha",
    },
    {
        "civil": "Neji Hyuga",
        "undercover": "Shoto Todoroki",
        "universe1": "Naruto",
        "universe2": "My Hero Academia",
        "archetype": "Génie Maudit",
        "wiki1": "naruto",
        "page1": "Neji Hyūga",
        "wiki2": "myheroacademia",
        "page2": "Shoto Todoroki",
    },
    {
        "civil": "L",
        "undercover": "Senku Ishigami",
        "universe1": "Death Note",
        "universe2": "Dr. Stone",
        "archetype": "Génie Maudit",
        "wiki1": "deathnote",
        "page1": "L (character)",
        "wiki2": "dr-stone",
        "page2": "Senku Ishigami",
    },
    {
        "civil": "Lelouch vi Britannia",
        "undercover": "Light Yagami",
        "universe1": "Code Geass",
        "universe2": "Death Note",
        "archetype": "Génie Maudit",
        "wiki1": "codegeass",
        "page1": "Lelouch vi Britannia",
        "wiki2": "deathnote",
        "page2": "Light Yagami",
    },
    {
        "civil": "Shikamaru Nara",
        "undercover": "L",
        "universe1": "Naruto",
        "universe2": "Death Note",
        "archetype": "Génie Maudit",
        "wiki1": "naruto",
        "page1": "Shikamaru Nara",
        "wiki2": "deathnote",
        "page2": "L (character)",
    },
    {
        "civil": "Itachi Uchiha",
        "undercover": "Killua Zoldyck",
        "universe1": "Naruto",
        "universe2": "Hunter x Hunter",
        "archetype": "Génie Maudit",
        "wiki1": "naruto",
        "page1": "Itachi Uchiha",
        "wiki2": "hunterxhunter",
        "page2": "Killua Zoldyck",
    },
    {
        "civil": "Toshiro Hitsugaya",
        "undercover": "Trunks",
        "universe1": "Bleach",
        "universe2": "Dragon Ball",
        "archetype": "Génie Maudit",
        "wiki1": "bleach",
        "page1": "Tōshirō Hitsugaya",
        "wiki2": "dragonball",
        "page2": "Trunks",
    },
    {
        "civil": "Ray",
        "undercover": "L",
        "universe1": "The Promised Neverland",
        "universe2": "Death Note",
        "archetype": "Génie Maudit",
        "wiki1": "yakusokunoneverland",
        "page1": "Ray",
        "wiki2": "deathnote",
        "page2": "L (character)",
    },
    {
        "civil": "Kurapika",
        "undercover": "Sasuke Uchiha",
        "universe1": "Hunter x Hunter",
        "universe2": "Naruto",
        "archetype": "Génie Maudit",
        "wiki1": "hunterxhunter",
        "page1": "Kurapika",
        "wiki2": "naruto",
        "page2": "Sasuke Uchiha",
    },
    {
        "civil": "Annie Leonhart",
        "undercover": "Killua Zoldyck",
        "universe1": "Attack on Titan",
        "universe2": "Hunter x Hunter",
        "archetype": "Génie Maudit",
        "wiki1": "attackontitan",
        "page1": "Annie Leonhart (Anime)",
        "wiki2": "hunterxhunter",
        "page2": "Killua Zoldyck",
    },

    # -------------------------------------------------------------------------
    # VILLAIN CHARISMATIQUE (10+)
    # -------------------------------------------------------------------------
    {
        "civil": "Pain",
        "undercover": "Eren Yeager",
        "universe1": "Naruto",
        "universe2": "Attack on Titan",
        "archetype": "Villain Charismatique",
        "wiki1": "naruto",
        "page1": "Nagato",
        "wiki2": "attackontitan",
        "page2": "Eren Yeager",
    },
    {
        "civil": "Meruem",
        "undercover": "Frieza",
        "universe1": "Hunter x Hunter",
        "universe2": "Dragon Ball",
        "archetype": "Villain Charismatique",
        "wiki1": "hunterxhunter",
        "page1": "Meruem",
        "wiki2": "dragonball",
        "page2": "Frieza",
    },
    {
        "civil": "Aizen Sosuke",
        "undercover": "Light Yagami",
        "universe1": "Bleach",
        "universe2": "Death Note",
        "archetype": "Villain Charismatique",
        "wiki1": "bleach",
        "page1": "Sousuke Aizen",
        "wiki2": "deathnote",
        "page2": "Light Yagami",
    },
    {
        "civil": "Madara Uchiha",
        "undercover": "Dio Brando",
        "universe1": "Naruto",
        "universe2": "JoJo's Bizarre Adventure",
        "archetype": "Villain Charismatique",
        "wiki1": "naruto",
        "page1": "Madara Uchiha",
        "wiki2": "jojo",
        "page2": "Dio Brando",
    },
    {
        "civil": "Griffith",
        "undercover": "Aizen Sosuke",
        "universe1": "Berserk",
        "universe2": "Bleach",
        "archetype": "Villain Charismatique",
        "wiki1": "berserk",
        "page1": "Griffith",
        "wiki2": "bleach",
        "page2": "Sousuke Aizen",
    },
    {
        "civil": "Hisoka Morow",
        "undercover": "Orochimaru",
        "universe1": "Hunter x Hunter",
        "universe2": "Naruto",
        "archetype": "Villain Charismatique",
        "wiki1": "hunterxhunter",
        "page1": "Hisoka Morow",
        "wiki2": "naruto",
        "page2": "Orochimaru",
    },
    {
        "civil": "Doflamingo",
        "undercover": "Dio Brando",
        "universe1": "One Piece",
        "universe2": "JoJo's Bizarre Adventure",
        "archetype": "Villain Charismatique",
        "wiki1": "onepiece",
        "page1": "Donquixote Doflamingo",
        "wiki2": "jojo",
        "page2": "Dio Brando",
    },
    {
        "civil": "Muzan Kibutsuji",
        "undercover": "Orochimaru",
        "universe1": "Demon Slayer",
        "universe2": "Naruto",
        "archetype": "Villain Charismatique",
        "wiki1": "kimetsu-no-yaiba",
        "page1": "Muzan Kibutsuji",
        "wiki2": "naruto",
        "page2": "Orochimaru",
    },
    {
        "civil": "Barbe Noire",
        "undercover": "Aizen Sosuke",
        "universe1": "One Piece",
        "universe2": "Bleach",
        "archetype": "Villain Charismatique",
        "wiki1": "onepiece",
        "page1": "Marshall D. Teach",
        "wiki2": "bleach",
        "page2": "Sousuke Aizen",
    },
    {
        "civil": "Chrollo Lucilfer",
        "undercover": "Itachi Uchiha",
        "universe1": "Hunter x Hunter",
        "universe2": "Naruto",
        "archetype": "Villain Charismatique",
        "wiki1": "hunterxhunter",
        "page1": "Chrollo Lucilfer",
        "wiki2": "naruto",
        "page2": "Itachi Uchiha",
    },
    {
        "civil": "Makima",
        "undercover": "Aizen Sosuke",
        "universe1": "Chainsaw Man",
        "universe2": "Bleach",
        "archetype": "Villain Charismatique",
        "wiki1": "chainsaw-man",
        "page1": "Makima",
        "wiki2": "bleach",
        "page2": "Sousuke Aizen",
    },

    # -------------------------------------------------------------------------
    # HEROS SOLAIRE (10+)
    # -------------------------------------------------------------------------
    {
        "civil": "Luffy",
        "undercover": "Naruto Uzumaki",
        "universe1": "One Piece",
        "universe2": "Naruto",
        "archetype": "Héros Solaire",
        "wiki1": "onepiece",
        "page1": "Monkey D. Luffy",
        "wiki2": "naruto",
        "page2": "Naruto Uzumaki",
    },
    {
        "civil": "Goku",
        "undercover": "Luffy",
        "universe1": "Dragon Ball",
        "universe2": "One Piece",
        "archetype": "Héros Solaire",
        "wiki1": "dragonball",
        "page1": "Goku",
        "wiki2": "onepiece",
        "page2": "Monkey D. Luffy",
    },
    {
        "civil": "Asta",
        "undercover": "Deku",
        "universe1": "Black Clover",
        "universe2": "My Hero Academia",
        "archetype": "Héros Solaire",
        "wiki1": "blackclover",
        "page1": "Asta",
        "wiki2": "myheroacademia",
        "page2": "Izuku Midoriya",
    },
    {
        "civil": "Natsu Dragneel",
        "undercover": "Luffy",
        "universe1": "Fairy Tail",
        "universe2": "One Piece",
        "archetype": "Héros Solaire",
        "wiki1": "fairytail",
        "page1": "Natsu Dragneel",
        "wiki2": "onepiece",
        "page2": "Monkey D. Luffy",
    },
    {
        "civil": "Gon Freecss",
        "undercover": "Luffy",
        "universe1": "Hunter x Hunter",
        "universe2": "One Piece",
        "archetype": "Héros Solaire",
        "wiki1": "hunterxhunter",
        "page1": "Gon Freecss",
        "wiki2": "onepiece",
        "page2": "Monkey D. Luffy",
    },
    {
        "civil": "Tanjiro Kamado",
        "undercover": "Deku",
        "universe1": "Demon Slayer",
        "universe2": "My Hero Academia",
        "archetype": "Héros Solaire",
        "wiki1": "kimetsu-no-yaiba",
        "page1": "Tanjiro Kamado",
        "wiki2": "myheroacademia",
        "page2": "Izuku Midoriya",
    },
    {
        "civil": "Naruto Uzumaki",
        "undercover": "Asta",
        "universe1": "Naruto",
        "universe2": "Black Clover",
        "archetype": "Héros Solaire",
        "wiki1": "naruto",
        "page1": "Naruto Uzumaki",
        "wiki2": "blackclover",
        "page2": "Asta",
    },
    {
        "civil": "Goku",
        "undercover": "Saitama",
        "universe1": "Dragon Ball",
        "universe2": "One Punch Man",
        "archetype": "Héros Solaire",
        "wiki1": "dragonball",
        "page1": "Goku",
        "wiki2": "onepunchman",
        "page2": "Saitama",
    },
    {
        "civil": "Natsu Dragneel",
        "undercover": "Asta",
        "universe1": "Fairy Tail",
        "universe2": "Black Clover",
        "archetype": "Héros Solaire",
        "wiki1": "fairytail",
        "page1": "Natsu Dragneel",
        "wiki2": "blackclover",
        "page2": "Asta",
    },
    {
        "civil": "Luffy",
        "undercover": "Gon Freecss",
        "universe1": "One Piece",
        "universe2": "Hunter x Hunter",
        "archetype": "Héros Solaire",
        "wiki1": "onepiece",
        "page1": "Monkey D. Luffy",
        "wiki2": "hunterxhunter",
        "page2": "Gon Freecss",
    },

    # -------------------------------------------------------------------------
    # RIVAL / DOUBLE INVERSE (10+)
    # -------------------------------------------------------------------------
    {
        "civil": "Goku",
        "undercover": "Vegeta",
        "universe1": "Dragon Ball",
        "universe2": "Dragon Ball",
        "archetype": "Rival / Double Inversé",
        "wiki1": "dragonball",
        "page1": "Goku",
        "wiki2": "dragonball",
        "page2": "Vegeta",
    },
    {
        "civil": "Naruto Uzumaki",
        "undercover": "Sasuke Uchiha",
        "universe1": "Naruto",
        "universe2": "Naruto",
        "archetype": "Rival / Double Inversé",
        "wiki1": "naruto",
        "page1": "Naruto Uzumaki",
        "wiki2": "naruto",
        "page2": "Sasuke Uchiha",
    },
    {
        "civil": "Edward Elric",
        "undercover": "Roy Mustang",
        "universe1": "Fullmetal Alchemist",
        "universe2": "Fullmetal Alchemist",
        "archetype": "Rival / Double Inversé",
        "wiki1": "fma",
        "page1": "Edward Elric",
        "wiki2": "fma",
        "page2": "Roy Mustang",
    },
    {
        "civil": "Bakugo",
        "undercover": "Vegeta",
        "universe1": "My Hero Academia",
        "universe2": "Dragon Ball",
        "archetype": "Rival / Double Inversé",
        "wiki1": "myheroacademia",
        "page1": "Katsuki Bakugo",
        "wiki2": "dragonball",
        "page2": "Vegeta",
    },
    {
        "civil": "Zoro",
        "undercover": "Vegeta",
        "universe1": "One Piece",
        "universe2": "Dragon Ball",
        "archetype": "Rival / Double Inversé",
        "wiki1": "onepiece",
        "page1": "Roronoa Zoro",
        "wiki2": "dragonball",
        "page2": "Vegeta",
    },
    {
        "civil": "Killua Zoldyck",
        "undercover": "Shoto Todoroki",
        "universe1": "Hunter x Hunter",
        "universe2": "My Hero Academia",
        "archetype": "Rival / Double Inversé",
        "wiki1": "hunterxhunter",
        "page1": "Killua Zoldyck",
        "wiki2": "myheroacademia",
        "page2": "Shoto Todoroki",
    },
    {
        "civil": "Grimmjow",
        "undercover": "Vegeta",
        "universe1": "Bleach",
        "universe2": "Dragon Ball",
        "archetype": "Rival / Double Inversé",
        "wiki1": "bleach",
        "page1": "Grimmjow Jaegerjaquez",
        "wiki2": "dragonball",
        "page2": "Vegeta",
    },
    {
        "civil": "Hiei",
        "undercover": "Vegeta",
        "universe1": "Yu Yu Hakusho",
        "universe2": "Dragon Ball",
        "archetype": "Rival / Double Inversé",
        "wiki1": "yuyuhakusho",
        "page1": "Hiei",
        "wiki2": "dragonball",
        "page2": "Vegeta",
    },
    {
        "civil": "Gojo Satoru",
        "undercover": "Sukuna",
        "universe1": "Jujutsu Kaisen",
        "universe2": "Jujutsu Kaisen",
        "archetype": "Rival / Double Inversé",
        "wiki1": "jujutsu-kaisen",
        "page1": "Satoru Gojo",
        "wiki2": "jujutsu-kaisen",
        "page2": "Sukuna",
    },
    {
        "civil": "Bakugo",
        "undercover": "Sasuke Uchiha",
        "universe1": "My Hero Academia",
        "universe2": "Naruto",
        "archetype": "Rival / Double Inversé",
        "wiki1": "myheroacademia",
        "page1": "Katsuki Bakugo",
        "wiki2": "naruto",
        "page2": "Sasuke Uchiha",
    },

    # -------------------------------------------------------------------------
    # PUISSANCE INCONTROLABLE (10+)
    # -------------------------------------------------------------------------
    {
        "civil": "Eren Yeager",
        "undercover": "Ken Kaneki",
        "universe1": "Attack on Titan",
        "universe2": "Tokyo Ghoul",
        "archetype": "Puissance Incontrôlable",
        "wiki1": "attackontitan",
        "page1": "Eren Yeager",
        "wiki2": "tokyoghoul",
        "page2": "Ken Kaneki",
    },
    {
        "civil": "Tetsuo Shima",
        "undercover": "Mob",
        "universe1": "Akira",
        "universe2": "Mob Psycho 100",
        "archetype": "Puissance Incontrôlable",
        "wiki1": "akira",
        "page1": "Tetsuo Shima",
        "wiki2": "mob-psycho-100",
        "page2": "Shigeo Kageyama",
    },
    {
        "civil": "Broly",
        "undercover": "Tetsuo Shima",
        "universe1": "Dragon Ball",
        "universe2": "Akira",
        "archetype": "Puissance Incontrôlable",
        "wiki1": "dragonball",
        "page1": "Broly (DBS)",
        "wiki2": "akira",
        "page2": "Tetsuo Shima",
    },
    {
        "civil": "Naruto (Kyuubi)",
        "undercover": "Ichigo Kurosaki",
        "universe1": "Naruto",
        "universe2": "Bleach",
        "archetype": "Puissance Incontrôlable",
        "wiki1": "naruto",
        "page1": "Naruto Uzumaki",
        "wiki2": "bleach",
        "page2": "Ichigo Kurosaki",
    },
    {
        "civil": "Ken Kaneki",
        "undercover": "Ichigo Kurosaki",
        "universe1": "Tokyo Ghoul",
        "universe2": "Bleach",
        "archetype": "Puissance Incontrôlable",
        "wiki1": "tokyoghoul",
        "page1": "Ken Kaneki",
        "wiki2": "bleach",
        "page2": "Ichigo Kurosaki",
    },
    {
        "civil": "Denji",
        "undercover": "Ken Kaneki",
        "universe1": "Chainsaw Man",
        "universe2": "Tokyo Ghoul",
        "archetype": "Puissance Incontrôlable",
        "wiki1": "chainsaw-man",
        "page1": "Denji",
        "wiki2": "tokyoghoul",
        "page2": "Ken Kaneki",
    },
    {
        "civil": "Gaara",
        "undercover": "Naruto Uzumaki",
        "universe1": "Naruto",
        "universe2": "Naruto",
        "archetype": "Puissance Incontrôlable",
        "wiki1": "naruto",
        "page1": "Gaara",
        "wiki2": "naruto",
        "page2": "Naruto Uzumaki",
    },
    {
        "civil": "Mob",
        "undercover": "Saitama",
        "universe1": "Mob Psycho 100",
        "universe2": "One Punch Man",
        "archetype": "Puissance Incontrôlable",
        "wiki1": "mob-psycho-100",
        "page1": "Shigeo Kageyama",
        "wiki2": "onepunchman",
        "page2": "Saitama",
    },
    {
        "civil": "Gon (Transformation)",
        "undercover": "Eren Yeager",
        "universe1": "Hunter x Hunter",
        "universe2": "Attack on Titan",
        "archetype": "Puissance Incontrôlable",
        "wiki1": "hunterxhunter",
        "page1": "Gon Freecss",
        "wiki2": "attackontitan",
        "page2": "Eren Yeager",
    },
    {
        "civil": "Shinji Ikari",
        "undercover": "Ken Kaneki",
        "universe1": "Evangelion",
        "universe2": "Tokyo Ghoul",
        "archetype": "Puissance Incontrôlable",
        "wiki1": "evangelion",
        "page1": "Shinji Ikari",
        "wiki2": "tokyoghoul",
        "page2": "Ken Kaneki",
    },

    # -------------------------------------------------------------------------
    # SACRIFIE PAR SON SYSTEME (10+)
    # -------------------------------------------------------------------------
    {
        "civil": "Itachi Uchiha",
        "undercover": "Reiner Braun",
        "universe1": "Naruto",
        "universe2": "Attack on Titan",
        "archetype": "Sacrifié par son Système",
        "wiki1": "naruto",
        "page1": "Itachi Uchiha",
        "wiki2": "attackontitan",
        "page2": "Reiner Braun (Anime)",
    },
    {
        "civil": "Giyu Tomioka",
        "undercover": "Levi Ackerman",
        "universe1": "Demon Slayer",
        "universe2": "Attack on Titan",
        "archetype": "Sacrifié par son Système",
        "wiki1": "kimetsu-no-yaiba",
        "page1": "Giyu Tomioka",
        "wiki2": "attackontitan",
        "page2": "Levi Ackerman",
    },
    {
        "civil": "Erwin Smith",
        "undercover": "Netero",
        "universe1": "Attack on Titan",
        "universe2": "Hunter x Hunter",
        "archetype": "Sacrifié par son Système",
        "wiki1": "attackontitan",
        "page1": "Erwin Smith (Anime)",
        "wiki2": "hunterxhunter",
        "page2": "Isaac Netero",
    },
    {
        "civil": "Kite",
        "undercover": "Jiraiya",
        "universe1": "Hunter x Hunter",
        "universe2": "Naruto",
        "archetype": "Sacrifié par son Système",
        "wiki1": "hunterxhunter",
        "page1": "Kite",
        "wiki2": "naruto",
        "page2": "Jiraiya",
    },
    {
        "civil": "Portgas D. Ace",
        "undercover": "Neji Hyuga",
        "universe1": "One Piece",
        "universe2": "Naruto",
        "archetype": "Sacrifié par son Système",
        "wiki1": "onepiece",
        "page1": "Portgas D. Ace",
        "wiki2": "naruto",
        "page2": "Neji Hyūga",
    },
    {
        "civil": "Riza Hawkeye",
        "undercover": "Mikasa Ackerman",
        "universe1": "Fullmetal Alchemist",
        "universe2": "Attack on Titan",
        "archetype": "Sacrifié par son Système",
        "wiki1": "fma",
        "page1": "Riza Hawkeye",
        "wiki2": "attackontitan",
        "page2": "Mikasa Ackerman",
    },
    {
        "civil": "Konan",
        "undercover": "Rukia Kuchiki",
        "universe1": "Naruto",
        "universe2": "Bleach",
        "archetype": "Sacrifié par son Système",
        "wiki1": "naruto",
        "page1": "Konan",
        "wiki2": "bleach",
        "page2": "Rukia Kuchiki",
    },
    {
        "civil": "Scar",
        "undercover": "Kurapika",
        "universe1": "Fullmetal Alchemist",
        "universe2": "Hunter x Hunter",
        "archetype": "Sacrifié par son Système",
        "wiki1": "fma",
        "page1": "Scar",
        "wiki2": "hunterxhunter",
        "page2": "Kurapika",
    },
    {
        "civil": "Marco Bott",
        "undercover": "Portgas D. Ace",
        "universe1": "Attack on Titan",
        "universe2": "One Piece",
        "archetype": "Sacrifié par son Système",
        "wiki1": "attackontitan",
        "page1": "Marco Bott",
        "wiki2": "onepiece",
        "page2": "Portgas D. Ace",
    },
    {
        "civil": "Maes Hughes",
        "undercover": "Kite",
        "universe1": "Fullmetal Alchemist",
        "universe2": "Hunter x Hunter",
        "archetype": "Sacrifié par son Système",
        "wiki1": "fma",
        "page1": "Maes Hughes",
        "wiki2": "hunterxhunter",
        "page2": "Kite",
    },

    # -------------------------------------------------------------------------
    # MIROIR HISTORIQUE (10+)
    # -------------------------------------------------------------------------
    {
        "civil": "Eren Yeager",
        "undercover": "Lelouch vi Britannia",
        "universe1": "Attack on Titan",
        "universe2": "Code Geass",
        "archetype": "Miroir Historique",
        "wiki1": "attackontitan",
        "page1": "Eren Yeager",
        "wiki2": "codegeass",
        "page2": "Lelouch vi Britannia",
    },
    {
        "civil": "King Bradley",
        "undercover": "Big Mom",
        "universe1": "Fullmetal Alchemist",
        "universe2": "One Piece",
        "archetype": "Miroir Historique",
        "wiki1": "fma",
        "page1": "King Bradley",
        "wiki2": "onepiece",
        "page2": "Charlotte Linlin",
    },
    {
        "civil": "Father",
        "undercover": "Muzan Kibutsuji",
        "universe1": "Fullmetal Alchemist",
        "universe2": "Demon Slayer",
        "archetype": "Miroir Historique",
        "wiki1": "fma",
        "page1": "Father",
        "wiki2": "kimetsu-no-yaiba",
        "page2": "Muzan Kibutsuji",
    },
    {
        "civil": "Scar",
        "undercover": "Eren Yeager",
        "universe1": "Fullmetal Alchemist",
        "universe2": "Attack on Titan",
        "archetype": "Miroir Historique",
        "wiki1": "fma",
        "page1": "Scar",
        "wiki2": "attackontitan",
        "page2": "Eren Yeager",
    },
    {
        "civil": "Roy Mustang",
        "undercover": "Erwin Smith",
        "universe1": "Fullmetal Alchemist",
        "universe2": "Attack on Titan",
        "archetype": "Miroir Historique",
        "wiki1": "fma",
        "page1": "Roy Mustang",
        "wiki2": "attackontitan",
        "page2": "Erwin Smith (Anime)",
    },
    {
        "civil": "Cornelia li Britannia",
        "undercover": "Esdeath",
        "universe1": "Code Geass",
        "universe2": "Akame ga Kill",
        "archetype": "Miroir Historique",
        "wiki1": "codegeass",
        "page1": "Cornelia li Britannia",
        "wiki2": "akamegakill",
        "page2": "Esdeath",
    },
    {
        "civil": "Doflamingo",
        "undercover": "King Bradley",
        "universe1": "One Piece",
        "universe2": "Fullmetal Alchemist",
        "archetype": "Miroir Historique",
        "wiki1": "onepiece",
        "page1": "Donquixote Doflamingo",
        "wiki2": "fma",
        "page2": "King Bradley",
    },
    {
        "civil": "Willy Tybur",
        "undercover": "Charles zi Britannia",
        "universe1": "Attack on Titan",
        "universe2": "Code Geass",
        "archetype": "Miroir Historique",
        "wiki1": "attackontitan",
        "page1": "Willy Tybur (Anime)",
        "wiki2": "codegeass",
        "page2": "Charles zi Britannia",
    },
    {
        "civil": "Muzan Kibutsuji",
        "undercover": "Father",
        "universe1": "Demon Slayer",
        "universe2": "Fullmetal Alchemist",
        "archetype": "Miroir Historique",
        "wiki1": "kimetsu-no-yaiba",
        "page1": "Muzan Kibutsuji",
        "wiki2": "fma",
        "page2": "Father",
    },
    {
        "civil": "Shou Tucker",
        "undercover": "Orochimaru",
        "universe1": "Fullmetal Alchemist",
        "universe2": "Naruto",
        "archetype": "Miroir Historique",
        "wiki1": "fma",
        "page1": "Shou Tucker",
        "wiki2": "naruto",
        "page2": "Orochimaru",
    },

    # -------------------------------------------------------------------------
    # ENTITE NON-HUMAINE QUI OBSERVE (8+)
    # -------------------------------------------------------------------------
    {
        "civil": "Ymir Fritz",
        "undercover": "Ryuk",
        "universe1": "Attack on Titan",
        "universe2": "Death Note",
        "archetype": "Entité Non-Humaine",
        "wiki1": "attackontitan",
        "page1": "Ymir Fritz (Anime)",
        "wiki2": "deathnote",
        "page2": "Ryuk",
    },
    {
        "civil": "Zeno",
        "undercover": "Truth",
        "universe1": "Dragon Ball",
        "universe2": "Fullmetal Alchemist",
        "archetype": "Entité Non-Humaine",
        "wiki1": "dragonball",
        "page1": "Zeno",
        "wiki2": "fma",
        "page2": "Truth",
    },
    {
        "civil": "Kaguya Otsutsuki",
        "undercover": "Yhwach",
        "universe1": "Naruto",
        "universe2": "Bleach",
        "archetype": "Entité Non-Humaine",
        "wiki1": "naruto",
        "page1": "Kaguya Ōtsutsuki",
        "wiki2": "bleach",
        "page2": "Yhwach",
    },
    {
        "civil": "Alluka Zoldyck",
        "undercover": "Ryuk",
        "universe1": "Hunter x Hunter",
        "universe2": "Death Note",
        "archetype": "Entité Non-Humaine",
        "wiki1": "hunterxhunter",
        "page1": "Alluka Zoldyck",
        "wiki2": "deathnote",
        "page2": "Ryuk",
    },
    {
        "civil": "Rimuru Tempest",
        "undercover": "Meruem",
        "universe1": "That Time I Got Reincarnated as a Slime",
        "universe2": "Hunter x Hunter",
        "archetype": "Entité Non-Humaine",
        "wiki1": "tensura",
        "page1": "Rimuru Tempest",
        "wiki2": "hunterxhunter",
        "page2": "Meruem",
    },
    {
        "civil": "Pochita",
        "undercover": "Kurama",
        "universe1": "Chainsaw Man",
        "universe2": "Naruto",
        "archetype": "Entité Non-Humaine",
        "wiki1": "chainsaw-man",
        "page1": "Pochita",
        "wiki2": "naruto",
        "page2": "Kurama",
    },
    {
        "civil": "Beerus",
        "undercover": "Sukuna",
        "universe1": "Dragon Ball",
        "universe2": "Jujutsu Kaisen",
        "archetype": "Entité Non-Humaine",
        "wiki1": "dragonball",
        "page1": "Beerus",
        "wiki2": "jujutsu-kaisen",
        "page2": "Sukuna",
    },
    {
        "civil": "Whis",
        "undercover": "Koro-sensei",
        "universe1": "Dragon Ball",
        "universe2": "Assassination Classroom",
        "archetype": "Entité Non-Humaine",
        "wiki1": "dragonball",
        "page1": "Whis",
        "wiki2": "ansatsukyoshitsu",
        "page2": "Korosensei",
    },

    # -------------------------------------------------------------------------
    # DUO INSEPARABLE (10+)
    # -------------------------------------------------------------------------
    {
        "civil": "Gon & Killua",
        "undercover": "Naruto & Sasuke",
        "universe1": "Hunter x Hunter",
        "universe2": "Naruto",
        "archetype": "Duo Inséparable",
        "wiki1": "hunterxhunter",
        "page1": "Gon Freecss",
        "wiki2": "naruto",
        "page2": "Naruto Uzumaki",
    },
    {
        "civil": "Luffy & Zoro",
        "undercover": "Goku & Vegeta",
        "universe1": "One Piece",
        "universe2": "Dragon Ball",
        "archetype": "Duo Inséparable",
        "wiki1": "onepiece",
        "page1": "Roronoa Zoro",
        "wiki2": "dragonball",
        "page2": "Vegeta",
    },
    {
        "civil": "Edward & Alphonse",
        "undercover": "Tanjiro & Nezuko",
        "universe1": "Fullmetal Alchemist",
        "universe2": "Demon Slayer",
        "archetype": "Duo Inséparable",
        "wiki1": "fma",
        "page1": "Alphonse Elric",
        "wiki2": "kimetsu-no-yaiba",
        "page2": "Nezuko Kamado",
    },
    {
        "civil": "Guts & Griffith",
        "undercover": "Naruto & Sasuke",
        "universe1": "Berserk",
        "universe2": "Naruto",
        "archetype": "Duo Inséparable",
        "wiki1": "berserk",
        "page1": "Guts",
        "wiki2": "naruto",
        "page2": "Sasuke Uchiha",
    },
    {
        "civil": "Eren & Mikasa",
        "undercover": "Naruto & Hinata",
        "universe1": "Attack on Titan",
        "universe2": "Naruto",
        "archetype": "Duo Inséparable",
        "wiki1": "attackontitan",
        "page1": "Mikasa Ackerman",
        "wiki2": "naruto",
        "page2": "Hinata Hyūga",
    },
    {
        "civil": "Meliodas & Ban",
        "undercover": "Goku & Vegeta",
        "universe1": "Seven Deadly Sins",
        "universe2": "Dragon Ball",
        "archetype": "Duo Inséparable",
        "wiki1": "nanatsu-no-taizai",
        "page1": "Meliodas",
        "wiki2": "dragonball",
        "page2": "Vegeta",
    },
    {
        "civil": "Levi & Erwin",
        "undercover": "Kakashi & Obito",
        "universe1": "Attack on Titan",
        "universe2": "Naruto",
        "archetype": "Duo Inséparable",
        "wiki1": "attackontitan",
        "page1": "Levi Ackerman",
        "wiki2": "naruto",
        "page2": "Obito Uchiha",
    },
    {
        "civil": "Simon & Kamina",
        "undercover": "Luffy & Ace",
        "universe1": "Gurren Lagann",
        "universe2": "One Piece",
        "archetype": "Duo Inséparable",
        "wiki1": "gurrenlagann",
        "page1": "Simon",
        "wiki2": "onepiece",
        "page2": "Portgas D. Ace",
    },
    {
        "civil": "Zoro & Sanji",
        "undercover": "Bakugo & Todoroki",
        "universe1": "One Piece",
        "universe2": "My Hero Academia",
        "archetype": "Duo Inséparable",
        "wiki1": "onepiece",
        "page1": "Sanji",
        "wiki2": "myheroacademia",
        "page2": "Shoto Todoroki",
    },
    {
        "civil": "Gintoki & Takasugi",
        "undercover": "Naruto & Sasuke",
        "universe1": "Gintama",
        "universe2": "Naruto",
        "archetype": "Duo Inséparable",
        "wiki1": "gintama",
        "page1": "Gintoki Sakata",
        "wiki2": "naruto",
        "page2": "Sasuke Uchiha",
    },

    # -------------------------------------------------------------------------
    # FEMME GUERRIERE BADASS (10+)
    # -------------------------------------------------------------------------
    {
        "civil": "Mikasa Ackerman",
        "undercover": "Casca",
        "universe1": "Attack on Titan",
        "universe2": "Berserk",
        "archetype": "Femme Guerrière Badass",
        "wiki1": "attackontitan",
        "page1": "Mikasa Ackerman",
        "wiki2": "berserk",
        "page2": "Casca",
    },
    {
        "civil": "Erza Scarlet",
        "undercover": "Mikasa Ackerman",
        "universe1": "Fairy Tail",
        "universe2": "Attack on Titan",
        "archetype": "Femme Guerrière Badass",
        "wiki1": "fairytail",
        "page1": "Erza Scarlet",
        "wiki2": "attackontitan",
        "page2": "Mikasa Ackerman",
    },
    {
        "civil": "Nobara Kugisaki",
        "undercover": "Sakura Haruno",
        "universe1": "Jujutsu Kaisen",
        "universe2": "Naruto",
        "archetype": "Femme Guerrière Badass",
        "wiki1": "jujutsu-kaisen",
        "page1": "Nobara Kugisaki",
        "wiki2": "naruto",
        "page2": "Sakura Haruno",
    },
    {
        "civil": "Android 18",
        "undercover": "Annie Leonhart",
        "universe1": "Dragon Ball",
        "universe2": "Attack on Titan",
        "archetype": "Femme Guerrière Badass",
        "wiki1": "dragonball",
        "page1": "Android 18",
        "wiki2": "attackontitan",
        "page2": "Annie Leonhart (Anime)",
    },
    {
        "civil": "Yoruichi Shihouin",
        "undercover": "Mirko",
        "universe1": "Bleach",
        "universe2": "My Hero Academia",
        "archetype": "Femme Guerrière Badass",
        "wiki1": "bleach",
        "page1": "Yoruichi Shihōin",
        "wiki2": "myheroacademia",
        "page2": "Rumi Usagiyama",
    },
    {
        "civil": "Tsunade",
        "undercover": "Unohana",
        "universe1": "Naruto",
        "universe2": "Bleach",
        "archetype": "Femme Guerrière Badass",
        "wiki1": "naruto",
        "page1": "Tsunade",
        "wiki2": "bleach",
        "page2": "Retsu Unohana",
    },
    {
        "civil": "Maki Zenin",
        "undercover": "Rock Lee",
        "universe1": "Jujutsu Kaisen",
        "universe2": "Naruto",
        "archetype": "Femme Guerrière Badass",
        "wiki1": "jujutsu-kaisen",
        "page1": "Maki Zenin",
        "wiki2": "naruto",
        "page2": "Rock Lee",
    },
    {
        "civil": "Nico Robin",
        "undercover": "Konan",
        "universe1": "One Piece",
        "universe2": "Naruto",
        "archetype": "Femme Guerrière Badass",
        "wiki1": "onepiece",
        "page1": "Nico Robin",
        "wiki2": "naruto",
        "page2": "Konan",
    },
    {
        "civil": "Power",
        "undercover": "Aqua",
        "universe1": "Chainsaw Man",
        "universe2": "Konosuba",
        "archetype": "Femme Guerrière Badass",
        "wiki1": "chainsaw-man",
        "page1": "Power",
        "wiki2": "konosuba",
        "page2": "Aqua",
    },
    {
        "civil": "Nami",
        "undercover": "Bulma",
        "universe1": "One Piece",
        "universe2": "Dragon Ball",
        "archetype": "Femme Guerrière Badass",
        "wiki1": "onepiece",
        "page1": "Nami",
        "wiki2": "dragonball",
        "page2": "Bulma",
    },

    # =========================================================================
    # INTRA-UNIVERSE PAIRS
    # =========================================================================

    # -------------------------------------------------------------------------
    # NARUTO (8+)
    # -------------------------------------------------------------------------
    {
        "civil": "Naruto Uzumaki",
        "undercover": "Minato Namikaze",
        "universe1": "Naruto",
        "universe2": "Naruto",
        "archetype": "Miroir Père-Fils",
        "wiki1": "naruto",
        "page1": "Naruto Uzumaki",
        "wiki2": "naruto",
        "page2": "Minato Namikaze",
    },
    {
        "civil": "Sasuke Uchiha",
        "undercover": "Itachi Uchiha",
        "universe1": "Naruto",
        "universe2": "Naruto",
        "archetype": "Miroir Frères",
        "wiki1": "naruto",
        "page1": "Sasuke Uchiha",
        "wiki2": "naruto",
        "page2": "Itachi Uchiha",
    },
    {
        "civil": "Kakashi Hatake",
        "undercover": "Obito Uchiha",
        "universe1": "Naruto",
        "universe2": "Naruto",
        "archetype": "Rival / Double Inversé",
        "wiki1": "naruto",
        "page1": "Kakashi Hatake",
        "wiki2": "naruto",
        "page2": "Obito Uchiha",
    },
    {
        "civil": "Jiraiya",
        "undercover": "Orochimaru",
        "universe1": "Naruto",
        "universe2": "Naruto",
        "archetype": "Rival / Double Inversé",
        "wiki1": "naruto",
        "page1": "Jiraiya",
        "wiki2": "naruto",
        "page2": "Orochimaru",
    },
    {
        "civil": "Sakura Haruno",
        "undercover": "Tsunade",
        "universe1": "Naruto",
        "universe2": "Naruto",
        "archetype": "Sensei Protecteur",
        "wiki1": "naruto",
        "page1": "Sakura Haruno",
        "wiki2": "naruto",
        "page2": "Tsunade",
    },
    {
        "civil": "Gaara",
        "undercover": "Naruto Uzumaki",
        "universe1": "Naruto",
        "universe2": "Naruto",
        "archetype": "Miroir Historique",
        "wiki1": "naruto",
        "page1": "Gaara",
        "wiki2": "naruto",
        "page2": "Naruto Uzumaki",
    },
    {
        "civil": "Madara Uchiha",
        "undercover": "Hashirama Senju",
        "universe1": "Naruto",
        "universe2": "Naruto",
        "archetype": "Rival / Double Inversé",
        "wiki1": "naruto",
        "page1": "Madara Uchiha",
        "wiki2": "naruto",
        "page2": "Hashirama Senju",
    },
    {
        "civil": "Hinata Hyuga",
        "undercover": "Neji Hyuga",
        "universe1": "Naruto",
        "universe2": "Naruto",
        "archetype": "Miroir Familial",
        "wiki1": "naruto",
        "page1": "Hinata Hyūga",
        "wiki2": "naruto",
        "page2": "Neji Hyūga",
    },
    {
        "civil": "Pain",
        "undercover": "Jiraiya",
        "universe1": "Naruto",
        "universe2": "Naruto",
        "archetype": "Sensei et Élève",
        "wiki1": "naruto",
        "page1": "Nagato",
        "wiki2": "naruto",
        "page2": "Jiraiya",
    },

    # -------------------------------------------------------------------------
    # DRAGON BALL (6+)
    # -------------------------------------------------------------------------
    {
        "civil": "Goku",
        "undercover": "Vegeta",
        "universe1": "Dragon Ball",
        "universe2": "Dragon Ball",
        "archetype": "Rival / Double Inversé",
        "wiki1": "dragonball",
        "page1": "Goku",
        "wiki2": "dragonball",
        "page2": "Vegeta",
    },
    {
        "civil": "Gohan",
        "undercover": "Trunks",
        "universe1": "Dragon Ball",
        "universe2": "Dragon Ball",
        "archetype": "Génie Maudit",
        "wiki1": "dragonball",
        "page1": "Gohan",
        "wiki2": "dragonball",
        "page2": "Trunks",
    },
    {
        "civil": "Frieza",
        "undercover": "Cell",
        "universe1": "Dragon Ball",
        "universe2": "Dragon Ball",
        "archetype": "Villain Charismatique",
        "wiki1": "dragonball",
        "page1": "Frieza",
        "wiki2": "dragonball",
        "page2": "Cell",
    },
    {
        "civil": "Piccolo",
        "undercover": "Vegeta",
        "universe1": "Dragon Ball",
        "universe2": "Dragon Ball",
        "archetype": "Rival / Double Inversé",
        "wiki1": "dragonball",
        "page1": "Piccolo",
        "wiki2": "dragonball",
        "page2": "Vegeta",
    },
    {
        "civil": "Goku",
        "undercover": "Broly",
        "universe1": "Dragon Ball",
        "universe2": "Dragon Ball",
        "archetype": "Puissance Incontrôlable",
        "wiki1": "dragonball",
        "page1": "Goku",
        "wiki2": "dragonball",
        "page2": "Broly (DBS)",
    },
    {
        "civil": "Beerus",
        "undercover": "Whis",
        "universe1": "Dragon Ball",
        "universe2": "Dragon Ball",
        "archetype": "Duo Inséparable",
        "wiki1": "dragonball",
        "page1": "Beerus",
        "wiki2": "dragonball",
        "page2": "Whis",
    },

    # -------------------------------------------------------------------------
    # ONE PIECE (8+)
    # -------------------------------------------------------------------------
    {
        "civil": "Luffy",
        "undercover": "Shanks",
        "universe1": "One Piece",
        "universe2": "One Piece",
        "archetype": "Sensei Protecteur",
        "wiki1": "onepiece",
        "page1": "Monkey D. Luffy",
        "wiki2": "onepiece",
        "page2": "Shanks",
    },
    {
        "civil": "Zoro",
        "undercover": "Mihawk",
        "universe1": "One Piece",
        "universe2": "One Piece",
        "archetype": "Rival / Double Inversé",
        "wiki1": "onepiece",
        "page1": "Roronoa Zoro",
        "wiki2": "onepiece",
        "page2": "Dracule Mihawk",
    },
    {
        "civil": "Sanji",
        "undercover": "Zoro",
        "universe1": "One Piece",
        "universe2": "One Piece",
        "archetype": "Rival / Double Inversé",
        "wiki1": "onepiece",
        "page1": "Sanji",
        "wiki2": "onepiece",
        "page2": "Roronoa Zoro",
    },
    {
        "civil": "Ace",
        "undercover": "Sabo",
        "universe1": "One Piece",
        "universe2": "One Piece",
        "archetype": "Miroir Frères",
        "wiki1": "onepiece",
        "page1": "Portgas D. Ace",
        "wiki2": "onepiece",
        "page2": "Sabo",
    },
    {
        "civil": "Luffy",
        "undercover": "Gol D. Roger",
        "universe1": "One Piece",
        "universe2": "One Piece",
        "archetype": "Miroir Historique",
        "wiki1": "onepiece",
        "page1": "Monkey D. Luffy",
        "wiki2": "onepiece",
        "page2": "Gol D. Roger",
    },
    {
        "civil": "Law",
        "undercover": "Corazon",
        "universe1": "One Piece",
        "universe2": "One Piece",
        "archetype": "Sensei Protecteur",
        "wiki1": "onepiece",
        "page1": "Trafalgar D. Water Law",
        "wiki2": "onepiece",
        "page2": "Donquixote Rosinante",
    },
    {
        "civil": "Nami",
        "undercover": "Robin",
        "universe1": "One Piece",
        "universe2": "One Piece",
        "archetype": "Duo Inséparable",
        "wiki1": "onepiece",
        "page1": "Nami",
        "wiki2": "onepiece",
        "page2": "Nico Robin",
    },
    {
        "civil": "Doflamingo",
        "undercover": "Crocodile",
        "universe1": "One Piece",
        "universe2": "One Piece",
        "archetype": "Villain Charismatique",
        "wiki1": "onepiece",
        "page1": "Donquixote Doflamingo",
        "wiki2": "onepiece",
        "page2": "Crocodile",
    },

    # -------------------------------------------------------------------------
    # BLEACH (5+)
    # -------------------------------------------------------------------------
    {
        "civil": "Ichigo Kurosaki",
        "undercover": "Aizen Sosuke",
        "universe1": "Bleach",
        "universe2": "Bleach",
        "archetype": "Rival / Double Inversé",
        "wiki1": "bleach",
        "page1": "Ichigo Kurosaki",
        "wiki2": "bleach",
        "page2": "Sousuke Aizen",
    },
    {
        "civil": "Rukia Kuchiki",
        "undercover": "Byakuya Kuchiki",
        "universe1": "Bleach",
        "universe2": "Bleach",
        "archetype": "Miroir Familial",
        "wiki1": "bleach",
        "page1": "Rukia Kuchiki",
        "wiki2": "bleach",
        "page2": "Byakuya Kuchiki",
    },
    {
        "civil": "Ichigo Kurosaki",
        "undercover": "Grimmjow",
        "universe1": "Bleach",
        "universe2": "Bleach",
        "archetype": "Rival / Double Inversé",
        "wiki1": "bleach",
        "page1": "Ichigo Kurosaki",
        "wiki2": "bleach",
        "page2": "Grimmjow Jaegerjaquez",
    },
    {
        "civil": "Urahara Kisuke",
        "undercover": "Aizen Sosuke",
        "universe1": "Bleach",
        "universe2": "Bleach",
        "archetype": "Génie Maudit",
        "wiki1": "bleach",
        "page1": "Kisuke Urahara",
        "wiki2": "bleach",
        "page2": "Sousuke Aizen",
    },
    {
        "civil": "Toshiro Hitsugaya",
        "undercover": "Rangiku Matsumoto",
        "universe1": "Bleach",
        "universe2": "Bleach",
        "archetype": "Duo Inséparable",
        "wiki1": "bleach",
        "page1": "Tōshirō Hitsugaya",
        "wiki2": "bleach",
        "page2": "Rangiku Matsumoto",
    },

    # -------------------------------------------------------------------------
    # ATTACK ON TITAN (5+)
    # -------------------------------------------------------------------------
    {
        "civil": "Eren Yeager",
        "undercover": "Reiner Braun",
        "universe1": "Attack on Titan",
        "universe2": "Attack on Titan",
        "archetype": "Miroir Historique",
        "wiki1": "attackontitan",
        "page1": "Eren Yeager",
        "wiki2": "attackontitan",
        "page2": "Reiner Braun (Anime)",
    },
    {
        "civil": "Levi Ackerman",
        "undercover": "Erwin Smith",
        "universe1": "Attack on Titan",
        "universe2": "Attack on Titan",
        "archetype": "Duo Inséparable",
        "wiki1": "attackontitan",
        "page1": "Levi Ackerman",
        "wiki2": "attackontitan",
        "page2": "Erwin Smith (Anime)",
    },
    {
        "civil": "Eren Yeager",
        "undercover": "Zeke Yeager",
        "universe1": "Attack on Titan",
        "universe2": "Attack on Titan",
        "archetype": "Miroir Frères",
        "wiki1": "attackontitan",
        "page1": "Eren Yeager",
        "wiki2": "attackontitan",
        "page2": "Zeke Yeager",
    },
    {
        "civil": "Mikasa Ackerman",
        "undercover": "Annie Leonhart",
        "universe1": "Attack on Titan",
        "universe2": "Attack on Titan",
        "archetype": "Femme Guerrière Badass",
        "wiki1": "attackontitan",
        "page1": "Mikasa Ackerman",
        "wiki2": "attackontitan",
        "page2": "Annie Leonhart (Anime)",
    },
    {
        "civil": "Armin Arlert",
        "undercover": "Erwin Smith",
        "universe1": "Attack on Titan",
        "universe2": "Attack on Titan",
        "archetype": "Génie Maudit",
        "wiki1": "attackontitan",
        "page1": "Armin Arlert",
        "wiki2": "attackontitan",
        "page2": "Erwin Smith (Anime)",
    },

    # -------------------------------------------------------------------------
    # MY HERO ACADEMIA (4+)
    # -------------------------------------------------------------------------
    {
        "civil": "Deku",
        "undercover": "Bakugo",
        "universe1": "My Hero Academia",
        "universe2": "My Hero Academia",
        "archetype": "Rival / Double Inversé",
        "wiki1": "myheroacademia",
        "page1": "Izuku Midoriya",
        "wiki2": "myheroacademia",
        "page2": "Katsuki Bakugo",
    },
    {
        "civil": "All Might",
        "undercover": "Endeavor",
        "universe1": "My Hero Academia",
        "universe2": "My Hero Academia",
        "archetype": "Rival / Double Inversé",
        "wiki1": "myheroacademia",
        "page1": "Toshinori Yagi",
        "wiki2": "myheroacademia",
        "page2": "Enji Todoroki",
    },
    {
        "civil": "Deku",
        "undercover": "All Might",
        "universe1": "My Hero Academia",
        "universe2": "My Hero Academia",
        "archetype": "Sensei Protecteur",
        "wiki1": "myheroacademia",
        "page1": "Izuku Midoriya",
        "wiki2": "myheroacademia",
        "page2": "Toshinori Yagi",
    },
    {
        "civil": "Todoroki",
        "undercover": "Endeavor",
        "universe1": "My Hero Academia",
        "universe2": "My Hero Academia",
        "archetype": "Miroir Père-Fils",
        "wiki1": "myheroacademia",
        "page1": "Shoto Todoroki",
        "wiki2": "myheroacademia",
        "page2": "Enji Todoroki",
    },

    # -------------------------------------------------------------------------
    # JUJUTSU KAISEN (4+)
    # -------------------------------------------------------------------------
    {
        "civil": "Gojo Satoru",
        "undercover": "Sukuna",
        "universe1": "Jujutsu Kaisen",
        "universe2": "Jujutsu Kaisen",
        "archetype": "Rival / Double Inversé",
        "wiki1": "jujutsu-kaisen",
        "page1": "Satoru Gojo",
        "wiki2": "jujutsu-kaisen",
        "page2": "Sukuna",
    },
    {
        "civil": "Yuji Itadori",
        "undercover": "Aoi Todo",
        "universe1": "Jujutsu Kaisen",
        "universe2": "Jujutsu Kaisen",
        "archetype": "Duo Inséparable",
        "wiki1": "jujutsu-kaisen",
        "page1": "Yuji Itadori",
        "wiki2": "jujutsu-kaisen",
        "page2": "Aoi Todo",
    },
    {
        "civil": "Gojo Satoru",
        "undercover": "Geto Suguru",
        "universe1": "Jujutsu Kaisen",
        "universe2": "Jujutsu Kaisen",
        "archetype": "Rival / Double Inversé",
        "wiki1": "jujutsu-kaisen",
        "page1": "Satoru Gojo",
        "wiki2": "jujutsu-kaisen",
        "page2": "Suguru Geto",
    },
    {
        "civil": "Megumi Fushiguro",
        "undercover": "Toji Fushiguro",
        "universe1": "Jujutsu Kaisen",
        "universe2": "Jujutsu Kaisen",
        "archetype": "Miroir Père-Fils",
        "wiki1": "jujutsu-kaisen",
        "page1": "Megumi Fushiguro",
        "wiki2": "jujutsu-kaisen",
        "page2": "Toji Fushiguro",
    },

    # -------------------------------------------------------------------------
    # DEMON SLAYER (4+)
    # -------------------------------------------------------------------------
    {
        "civil": "Tanjiro Kamado",
        "undercover": "Inosuke Hashibira",
        "universe1": "Demon Slayer",
        "universe2": "Demon Slayer",
        "archetype": "Duo Inséparable",
        "wiki1": "kimetsu-no-yaiba",
        "page1": "Tanjiro Kamado",
        "wiki2": "kimetsu-no-yaiba",
        "page2": "Inosuke Hashibira",
    },
    {
        "civil": "Tanjiro Kamado",
        "undercover": "Zenitsu Agatsuma",
        "universe1": "Demon Slayer",
        "universe2": "Demon Slayer",
        "archetype": "Duo Inséparable",
        "wiki1": "kimetsu-no-yaiba",
        "page1": "Tanjiro Kamado",
        "wiki2": "kimetsu-no-yaiba",
        "page2": "Zenitsu Agatsuma",
    },
    {
        "civil": "Muzan Kibutsuji",
        "undercover": "Tamayo",
        "universe1": "Demon Slayer",
        "universe2": "Demon Slayer",
        "archetype": "Miroir Historique",
        "wiki1": "kimetsu-no-yaiba",
        "page1": "Muzan Kibutsuji",
        "wiki2": "kimetsu-no-yaiba",
        "page2": "Tamayo",
    },
    {
        "civil": "Giyu Tomioka",
        "undercover": "Sanemi Shinazugawa",
        "universe1": "Demon Slayer",
        "universe2": "Demon Slayer",
        "archetype": "Rival / Double Inversé",
        "wiki1": "kimetsu-no-yaiba",
        "page1": "Giyu Tomioka",
        "wiki2": "kimetsu-no-yaiba",
        "page2": "Sanemi Shinazugawa",
    },

    # -------------------------------------------------------------------------
    # DEATH NOTE (3+)
    # -------------------------------------------------------------------------
    {
        "civil": "Light Yagami",
        "undercover": "L",
        "universe1": "Death Note",
        "universe2": "Death Note",
        "archetype": "Rival / Double Inversé",
        "wiki1": "deathnote",
        "page1": "Light Yagami",
        "wiki2": "deathnote",
        "page2": "L (character)",
    },
    {
        "civil": "Misa Amane",
        "undercover": "Rem",
        "universe1": "Death Note",
        "universe2": "Death Note",
        "archetype": "Duo Inséparable",
        "wiki1": "deathnote",
        "page1": "Misa Amane",
        "wiki2": "deathnote",
        "page2": "Rem",
    },
    {
        "civil": "Near",
        "undercover": "Mello",
        "universe1": "Death Note",
        "universe2": "Death Note",
        "archetype": "Rival / Double Inversé",
        "wiki1": "deathnote",
        "page1": "Near",
        "wiki2": "deathnote",
        "page2": "Mello",
    },

    # -------------------------------------------------------------------------
    # HUNTER X HUNTER (4+)
    # -------------------------------------------------------------------------
    {
        "civil": "Gon Freecss",
        "undercover": "Killua Zoldyck",
        "universe1": "Hunter x Hunter",
        "universe2": "Hunter x Hunter",
        "archetype": "Duo Inséparable",
        "wiki1": "hunterxhunter",
        "page1": "Gon Freecss",
        "wiki2": "hunterxhunter",
        "page2": "Killua Zoldyck",
    },
    {
        "civil": "Hisoka Morow",
        "undercover": "Chrollo Lucilfer",
        "universe1": "Hunter x Hunter",
        "universe2": "Hunter x Hunter",
        "archetype": "Villain Charismatique",
        "wiki1": "hunterxhunter",
        "page1": "Hisoka Morow",
        "wiki2": "hunterxhunter",
        "page2": "Chrollo Lucilfer",
    },
    {
        "civil": "Kurapika",
        "undercover": "Brigade Fantôme",
        "universe1": "Hunter x Hunter",
        "universe2": "Hunter x Hunter",
        "archetype": "Sacrifié par son Système",
        "wiki1": "hunterxhunter",
        "page1": "Kurapika",
        "wiki2": "hunterxhunter",
        "page2": "Phantom Troupe",
    },
    {
        "civil": "Netero",
        "undercover": "Meruem",
        "universe1": "Hunter x Hunter",
        "universe2": "Hunter x Hunter",
        "archetype": "Rival / Double Inversé",
        "wiki1": "hunterxhunter",
        "page1": "Isaac Netero",
        "wiki2": "hunterxhunter",
        "page2": "Meruem",
    },

    # -------------------------------------------------------------------------
    # FULLMETAL ALCHEMIST (4+)
    # -------------------------------------------------------------------------
    {
        "civil": "Edward Elric",
        "undercover": "Roy Mustang",
        "universe1": "Fullmetal Alchemist",
        "universe2": "Fullmetal Alchemist",
        "archetype": "Rival / Double Inversé",
        "wiki1": "fma",
        "page1": "Edward Elric",
        "wiki2": "fma",
        "page2": "Roy Mustang",
    },
    {
        "civil": "Scar",
        "undercover": "Kimblee",
        "universe1": "Fullmetal Alchemist",
        "universe2": "Fullmetal Alchemist",
        "archetype": "Miroir Historique",
        "wiki1": "fma",
        "page1": "Scar",
        "wiki2": "fma",
        "page2": "Solf J. Kimblee",
    },
    {
        "civil": "Hohenheim",
        "undercover": "Father",
        "universe1": "Fullmetal Alchemist",
        "universe2": "Fullmetal Alchemist",
        "archetype": "Rival / Double Inversé",
        "wiki1": "fma",
        "page1": "Van Hohenheim",
        "wiki2": "fma",
        "page2": "Father",
    },
    {
        "civil": "Winry Rockbell",
        "undercover": "Riza Hawkeye",
        "universe1": "Fullmetal Alchemist",
        "universe2": "Fullmetal Alchemist",
        "archetype": "Femme Guerrière Badass",
        "wiki1": "fma",
        "page1": "Winry Rockbell",
        "wiki2": "fma",
        "page2": "Riza Hawkeye",
    },

    # =========================================================================
    # MODE SHŌJO 🌸 - emotional, relationships, strong female characters
    # =========================================================================
    {
        "civil": "Usagi Tsukino",
        "undercover": "Sakura Kinomoto",
        "universe1": "Sailor Moon",
        "universe2": "Cardcaptor Sakura",
        "archetype": "Magical Girl qui protège par l'amour",
        "wiki1": "sailormoon",
        "page1": "Usagi Tsukino",
        "wiki2": "cardcaptor-sakura",
        "page2": "Sakura Kinomoto",
        "mode": "shojo",
    },
    {
        "civil": "Tohru Honda",
        "undercover": "Sawako Kuronuma",
        "universe1": "Fruits Basket",
        "universe2": "Kimi ni Todoke",
        "archetype": "Fille timide et gentille qui change tout le monde",
        "wiki1": "fruitsbasket",
        "page1": "Tohru Honda",
        "wiki2": "kimi-ni-todoke",
        "page2": "Sawako Kuronuma",
        "mode": "shojo",
    },
    {
        "civil": "Tamaki Suoh",
        "undercover": "Kyo Sohma",
        "universe1": "Ouran High School Host Club",
        "universe2": "Fruits Basket",
        "archetype": "Love interest dramatique cachant une douleur",
        "wiki1": "ouran-high-school-host-club",
        "page1": "Tamaki Suoh",
        "wiki2": "fruitsbasket",
        "page2": "Kyo Sohma",
        "mode": "shojo",
    },
    {
        "civil": "Violet Evergarden",
        "undercover": "Rei Ayanami",
        "universe1": "Violet Evergarden",
        "universe2": "Neon Genesis Evangelion",
        "archetype": "Fille sans émotions apprenant à ressentir",
        "wiki1": "violet-evergarden",
        "page1": "Violet Evergarden",
        "wiki2": "evangelion",
        "page2": "Rei Ayanami",
        "mode": "shojo",
    },
    {
        "civil": "Kaori Miyazono",
        "undercover": "Nagisa Furukawa",
        "universe1": "Your Lie in April",
        "universe2": "Clannad",
        "archetype": "Fille dont la vie est tragiquement courte",
        "wiki1": "shigatsu-wa-kimi-no-uso",
        "page1": "Kaori Miyazono",
        "wiki2": "clannad",
        "page2": "Nagisa Furukawa",
        "mode": "shojo",
    },
    {
        "civil": "Taiga Aisaka",
        "undercover": "Asuka Langley",
        "universe1": "Toradora",
        "universe2": "Neon Genesis Evangelion",
        "archetype": "Tsundere agressive cachant sa vulnérabilité",
        "wiki1": "toradora",
        "page1": "Taiga Aisaka",
        "wiki2": "evangelion",
        "page2": "Asuka Langley Soryu",
        "mode": "shojo",
    },
    {
        "civil": "Sailor Moon",
        "undercover": "Madoka Kaname",
        "universe1": "Sailor Moon",
        "universe2": "Puella Magi Madoka Magica",
        "archetype": "Magical Girl qui sacrifie tout",
        "wiki1": "sailormoon",
        "page1": "Usagi Tsukino",
        "wiki2": "puella-magi-wiki",
        "page2": "Madoka Kaname",
        "mode": "shojo",
    },
    {
        "civil": "Haruhi Fujioka",
        "undercover": "Tohru Honda",
        "universe1": "Ouran High School Host Club",
        "universe2": "Fruits Basket",
        "archetype": "Fille ordinaire dans un monde extraordinaire",
        "wiki1": "ouran-high-school-host-club",
        "page1": "Haruhi Fujioka",
        "wiki2": "fruitsbasket",
        "page2": "Tohru Honda",
        "mode": "shojo",
    },
    {
        "civil": "Tomoya Okazaki",
        "undercover": "Kousei Arima",
        "universe1": "Clannad",
        "universe2": "Your Lie in April",
        "archetype": "Garçon brisé guéri par l'amour",
        "wiki1": "clannad",
        "page1": "Tomoya Okazaki",
        "wiki2": "shigatsu-wa-kimi-no-uso",
        "page2": "Kousei Arima",
        "mode": "shojo",
    },
    {
        "civil": "Momiji Sohma",
        "undercover": "Honey Senpai",
        "universe1": "Fruits Basket",
        "universe2": "Ouran High School Host Club",
        "archetype": "Garçon mignon cachant une profonde tristesse",
        "wiki1": "fruitsbasket",
        "page1": "Momiji Sohma",
        "wiki2": "ouran-high-school-host-club",
        "page2": "Mitsukuni Haninozuka",
        "mode": "shojo",
    },
    {
        "civil": "Akito Sohma",
        "undercover": "Ciel Phantomhive",
        "universe1": "Fruits Basket",
        "universe2": "Black Butler",
        "archetype": "Enfant cruel façonné par le traumatisme",
        "wiki1": "fruitsbasket",
        "page1": "Akito Sohma",
        "wiki2": "blackbutler",
        "page2": "Ciel Phantomhive",
        "mode": "shojo",
    },
    {
        "civil": "Sailor Mars",
        "undercover": "Erza Scarlet",
        "universe1": "Sailor Moon",
        "universe2": "Fairy Tail",
        "archetype": "Guerrière féroce au cœur tendre",
        "wiki1": "sailormoon",
        "page1": "Rei Hino",
        "wiki2": "fairytail",
        "page2": "Erza Scarlet",
        "mode": "shojo",
    },
    {
        "civil": "Tomoyo Daidouji",
        "undercover": "Mitsuki Koyama",
        "universe1": "Cardcaptor Sakura",
        "universe2": "Full Moon wo Sagashite",
        "archetype": "Amie dévouée qui soutient dans l'ombre",
        "wiki1": "cardcaptor-sakura",
        "page1": "Tomoyo Daidouji",
        "wiki2": "fullmoon",
        "page2": "Mitsuki Koyama",
        "mode": "shojo",
    },
    {
        "civil": "Syaoran Li",
        "undercover": "Kyo Sohma",
        "universe1": "Cardcaptor Sakura",
        "universe2": "Fruits Basket",
        "archetype": "Garçon tsundere qui s'adoucit pour une fille",
        "wiki1": "cardcaptor-sakura",
        "page1": "Syaoran Li",
        "wiki2": "fruitsbasket",
        "page2": "Kyo Sohma",
        "mode": "shojo",
    },
    {
        "civil": "Chibiusa",
        "undercover": "Nunnally vi Britannia",
        "universe1": "Sailor Moon",
        "universe2": "Code Geass",
        "archetype": "Enfant innocente que tout le monde protège",
        "wiki1": "sailormoon",
        "page1": "Chibiusa",
        "wiki2": "codegeass",
        "page2": "Nunnally vi Britannia",
        "mode": "shojo",
    },
    {
        "civil": "Yuki Sohma",
        "undercover": "Tamaki Suoh",
        "universe1": "Fruits Basket",
        "universe2": "Ouran High School Host Club",
        "archetype": "Prince cachant sa solitude",
        "wiki1": "fruitsbasket",
        "page1": "Yuki Sohma",
        "wiki2": "ouran-high-school-host-club",
        "page2": "Tamaki Suoh",
        "mode": "shojo",
    },
    {
        "civil": "Sakura Kinomoto",
        "undercover": "Nanoha Takamachi",
        "universe1": "Cardcaptor Sakura",
        "universe2": "Magical Girl Lyrical Nanoha",
        "archetype": "Magical Girl qui se lie d'amitié avec ses ennemis",
        "wiki1": "cardcaptor-sakura",
        "page1": "Sakura Kinomoto",
        "wiki2": "nanoha",
        "page2": "Nanoha Takamachi",
        "mode": "shojo",
    },
    {
        "civil": "Misaki Ayuzawa",
        "undercover": "Haruhi Fujioka",
        "universe1": "Maid Sama",
        "universe2": "Ouran High School Host Club",
        "archetype": "Fille forte dans un monde dominé par les hommes",
        "wiki1": "kaichou-wa-maid-sama",
        "page1": "Misaki Ayuzawa",
        "wiki2": "ouran-high-school-host-club",
        "page2": "Haruhi Fujioka",
        "mode": "shojo",
    },
    {
        "civil": "Usui Takumi",
        "undercover": "Tamaki Suoh",
        "universe1": "Maid Sama",
        "universe2": "Ouran High School Host Club",
        "archetype": "Garçon riche mystérieux et parfait",
        "wiki1": "kaichou-wa-maid-sama",
        "page1": "Takumi Usui",
        "wiki2": "ouran-high-school-host-club",
        "page2": "Tamaki Suoh",
        "mode": "shojo",
    },
    {
        "civil": "Hotaru Tomoe",
        "undercover": "Homura Akemi",
        "universe1": "Sailor Moon",
        "universe2": "Puella Magi Madoka Magica",
        "archetype": "Magical Girl sombre dévouée à une seule personne",
        "wiki1": "sailormoon",
        "page1": "Hotaru Tomoe",
        "wiki2": "puella-magi-wiki",
        "page2": "Homura Akemi",
        "mode": "shojo",
    },

    # =========================================================================
    # MODE ISEKAI 🌀 - transported to another world
    # =========================================================================
    {
        "civil": "Subaru Natsuki",
        "undercover": "Kazuma Satou",
        "universe1": "Re:Zero",
        "universe2": "KonoSuba",
        "archetype": "Gars ordinaire dans un monde fantasy",
        "wiki1": "re-zero",
        "page1": "Subaru Natsuki",
        "wiki2": "konosuba",
        "page2": "Kazuma Satou",
        "mode": "isekai",
    },
    {
        "civil": "Rimuru Tempest",
        "undercover": "Ainz Ooal Gown",
        "universe1": "That Time I Got Reincarnated as a Slime",
        "universe2": "Overlord",
        "archetype": "Leader réincarné surpuissant",
        "wiki1": "tensura",
        "page1": "Rimuru Tempest",
        "wiki2": "overlordmaruyama",
        "page2": "Ainz Ooal Gown",
        "mode": "isekai",
    },
    {
        "civil": "Kirito",
        "undercover": "Naofumi Iwatani",
        "universe1": "Sword Art Online",
        "universe2": "The Rising of the Shield Hero",
        "archetype": "Joueur solo devenu légendaire",
        "wiki1": "swordartonline",
        "page1": "Kirito",
        "wiki2": "shield-hero",
        "page2": "Naofumi Iwatani",
        "mode": "isekai",
    },
    {
        "civil": "Emilia",
        "undercover": "Raphtalia",
        "universe1": "Re:Zero",
        "universe2": "The Rising of the Shield Hero",
        "archetype": "Héroïne dévouée qui croit en le héros",
        "wiki1": "re-zero",
        "page1": "Emilia",
        "wiki2": "shield-hero",
        "page2": "Raphtalia",
        "mode": "isekai",
    },
    {
        "civil": "Rem",
        "undercover": "Asuna",
        "universe1": "Re:Zero",
        "universe2": "Sword Art Online",
        "archetype": "Fille dévouée qui combat aux côtés du héros",
        "wiki1": "re-zero",
        "page1": "Rem",
        "wiki2": "swordartonline",
        "page2": "Asuna",
        "mode": "isekai",
    },
    {
        "civil": "Aqua",
        "undercover": "Megumin",
        "universe1": "KonoSuba",
        "universe2": "KonoSuba",
        "archetype": "Compagne féminine chaotique",
        "wiki1": "konosuba",
        "page1": "Aqua",
        "wiki2": "konosuba",
        "page2": "Megumin",
        "mode": "isekai",
    },
    {
        "civil": "Rudeus Greyrat",
        "undercover": "Subaru Natsuki",
        "universe1": "Mushoku Tensei",
        "universe2": "Re:Zero",
        "archetype": "Protagoniste isekai imparfait qui grandit",
        "wiki1": "mushoku-tensei",
        "page1": "Rudeus Greyrat",
        "wiki2": "re-zero",
        "page2": "Subaru Natsuki",
        "mode": "isekai",
    },
    {
        "civil": "Ainz Ooal Gown",
        "undercover": "Diablo",
        "universe1": "Overlord",
        "universe2": "How Not to Summon a Demon Lord",
        "archetype": "Protagoniste isekai de type vilain",
        "wiki1": "overlordmaruyama",
        "page1": "Ainz Ooal Gown",
        "wiki2": "how-not-to-summon-a-demon-lord",
        "page2": "Diablo",
        "mode": "isekai",
    },
    {
        "civil": "Raphtalia",
        "undercover": "Rem",
        "universe1": "The Rising of the Shield Hero",
        "universe2": "Re:Zero",
        "archetype": "Compagne loyale tombée amoureuse du héros",
        "wiki1": "shield-hero",
        "page1": "Raphtalia",
        "wiki2": "re-zero",
        "page2": "Rem",
        "mode": "isekai",
    },
    {
        "civil": "Albedo",
        "undercover": "Rem",
        "universe1": "Overlord",
        "universe2": "Re:Zero",
        "archetype": "Dévouée obsessionnellement à son maître",
        "wiki1": "overlordmaruyama",
        "page1": "Albedo",
        "wiki2": "re-zero",
        "page2": "Rem",
        "mode": "isekai",
    },
    {
        "civil": "Shalltear Bloodfallen",
        "undercover": "Emilia",
        "universe1": "Overlord",
        "universe2": "Re:Zero",
        "archetype": "Femme puissante dans un monde politique",
        "wiki1": "overlordmaruyama",
        "page1": "Shalltear Bloodfallen",
        "wiki2": "re-zero",
        "page2": "Emilia",
        "mode": "isekai",
    },
    {
        "civil": "Kirito",
        "undercover": "Rudeus Greyrat",
        "universe1": "Sword Art Online",
        "universe2": "Mushoku Tensei",
        "archetype": "Prodige qui maîtrise son nouveau monde",
        "wiki1": "swordartonline",
        "page1": "Kirito",
        "wiki2": "mushoku-tensei",
        "page2": "Rudeus Greyrat",
        "mode": "isekai",
    },
    {
        "civil": "Darkness",
        "undercover": "Raphtalia",
        "universe1": "KonoSuba",
        "universe2": "The Rising of the Shield Hero",
        "archetype": "Compagne chevalière",
        "wiki1": "konosuba",
        "page1": "Darkness",
        "wiki2": "shield-hero",
        "page2": "Raphtalia",
        "mode": "isekai",
    },
    {
        "civil": "Reinhard van Astrea",
        "undercover": "Kirito",
        "universe1": "Re:Zero",
        "universe2": "Sword Art Online",
        "archetype": "Épéiste surpuissant",
        "wiki1": "re-zero",
        "page1": "Reinhard van Astrea",
        "wiki2": "swordartonline",
        "page2": "Kirito",
        "mode": "isekai",
    },
    {
        "civil": "Roswaal L Mathers",
        "undercover": "Ainz Ooal Gown",
        "universe1": "Re:Zero",
        "universe2": "Overlord",
        "archetype": "Manipulateur puissant et mystérieux",
        "wiki1": "re-zero",
        "page1": "Roswaal L Mathers",
        "wiki2": "overlordmaruyama",
        "page2": "Ainz Ooal Gown",
        "mode": "isekai",
    },
    {
        "civil": "Wiz",
        "undercover": "Albedo",
        "universe1": "KonoSuba",
        "universe2": "Overlord",
        "archetype": "Puissante utilisatrice de magie",
        "wiki1": "konosuba",
        "page1": "Wiz",
        "wiki2": "overlordmaruyama",
        "page2": "Albedo",
        "mode": "isekai",
    },
    {
        "civil": "Shiro",
        "undercover": "Rimuru Tempest",
        "universe1": "No Game No Life",
        "universe2": "That Time I Got Reincarnated as a Slime",
        "archetype": "Stratège génial dans un monde fantasy",
        "wiki1": "no-game-no-life",
        "page1": "Shiro",
        "wiki2": "tensura",
        "page2": "Rimuru Tempest",
        "mode": "isekai",
    },
    {
        "civil": "Sora",
        "undercover": "Kazuma Satou",
        "universe1": "No Game No Life",
        "universe2": "KonoSuba",
        "archetype": "NEET qui prospère dans un monde de jeu",
        "wiki1": "no-game-no-life",
        "page1": "Sora",
        "wiki2": "konosuba",
        "page2": "Kazuma Satou",
        "mode": "isekai",
    },
    {
        "civil": "Subaru Natsuki",
        "undercover": "Naofumi Iwatani",
        "universe1": "Re:Zero",
        "universe2": "The Rising of the Shield Hero",
        "archetype": "Héros qui souffre sans fin mais n'abandonne jamais",
        "wiki1": "re-zero",
        "page1": "Subaru Natsuki",
        "wiki2": "shield-hero",
        "page2": "Naofumi Iwatani",
        "mode": "isekai",
    },
    {
        "civil": "Echidna",
        "undercover": "Shalltear Bloodfallen",
        "universe1": "Re:Zero",
        "universe2": "Overlord",
        "archetype": "Femme vilaine élégante",
        "wiki1": "re-zero",
        "page1": "Echidna",
        "wiki2": "overlordmaruyama",
        "page2": "Shalltear Bloodfallen",
        "mode": "isekai",
    },

    # =========================================================================
    # MODE CLASSIQUE 👴 - Pre-2010 anime
    # =========================================================================
    {
        "civil": "Pegasus Seiya",
        "undercover": "Goku",
        "universe1": "Saint Seiya",
        "universe2": "Dragon Ball",
        "archetype": "Combattant au cœur pur qui n'abandonne jamais",
        "wiki1": "saintseiya",
        "page1": "Pegasus Seiya",
        "wiki2": "dragonball",
        "page2": "Goku",
        "mode": "classic",
    },
    {
        "civil": "Hanamichi Sakuragi",
        "undercover": "Naruto Uzumaki",
        "universe1": "Slam Dunk",
        "universe2": "Naruto",
        "archetype": "Underdog bruyant qui prouve que tout le monde a tort",
        "wiki1": "slamdunk",
        "page1": "Hanamichi Sakuragi",
        "wiki2": "naruto",
        "page2": "Naruto Uzumaki",
        "mode": "classic",
    },
    {
        "civil": "Inuyasha",
        "undercover": "Vegeta",
        "universe1": "Inuyasha",
        "universe2": "Dragon Ball",
        "archetype": "Guerrier orgueilleux adouci par l'amour",
        "wiki1": "inuyasha",
        "page1": "Inuyasha",
        "wiki2": "dragonball",
        "page2": "Vegeta",
        "mode": "classic",
    },
    {
        "civil": "Kenshiro",
        "undercover": "Guts",
        "universe1": "Hokuto no Ken",
        "universe2": "Berserk",
        "archetype": "Guerrier inarrêtable dans un monde post-apocalyptique",
        "wiki1": "hokuto",
        "page1": "Kenshiro",
        "wiki2": "berserk",
        "page2": "Guts",
        "mode": "classic",
    },
    {
        "civil": "Ranma Saotome",
        "undercover": "Inuyasha",
        "universe1": "Ranma ½",
        "universe2": "Inuyasha",
        "archetype": "Artiste martial avec une malédiction",
        "wiki1": "ranma",
        "page1": "Ranma Saotome",
        "wiki2": "inuyasha",
        "page2": "Inuyasha",
        "mode": "classic",
    },
    {
        "civil": "Yugi Mutou",
        "undercover": "Gon Freecss",
        "universe1": "Yu-Gi-Oh!",
        "universe2": "Hunter x Hunter",
        "archetype": "Garçon innocent avec un pouvoir caché",
        "wiki1": "yugioh",
        "page1": "Yugi Mutou",
        "wiki2": "hunterxhunter",
        "page2": "Gon Freecss",
        "mode": "classic",
    },
    {
        "civil": "Tsubasa Ozora",
        "undercover": "Hanamichi Sakuragi",
        "universe1": "Captain Tsubasa",
        "universe2": "Slam Dunk",
        "archetype": "Prodige sportif porté par la passion",
        "wiki1": "captaintsubasa",
        "page1": "Tsubasa Ozora",
        "wiki2": "slamdunk",
        "page2": "Hanamichi Sakuragi",
        "mode": "classic",
    },
    {
        "civil": "Gintoki Sakata",
        "undercover": "Spike Spiegel",
        "universe1": "Gintama",
        "universe2": "Cowboy Bebop",
        "archetype": "Gars cool et paresseux cachant un passé de guerrier",
        "wiki1": "gintama",
        "page1": "Gintoki Sakata",
        "wiki2": "cowboy-bebop",
        "page2": "Spike Spiegel",
        "mode": "classic",
    },
    {
        "civil": "Himura Kenshin",
        "undercover": "Kenshiro",
        "universe1": "Rurouni Kenshin",
        "universe2": "Hokuto no Ken",
        "archetype": "Guerrier légendaire cherchant la paix",
        "wiki1": "rurounikenshin",
        "page1": "Himura Kenshin",
        "wiki2": "hokuto",
        "page2": "Kenshiro",
        "mode": "classic",
    },
    {
        "civil": "Vash the Stampede",
        "undercover": "Gintoki Sakata",
        "universe1": "Trigun",
        "universe2": "Gintama",
        "archetype": "Pitre cachant une puissance immense",
        "wiki1": "trigun",
        "page1": "Vash the Stampede",
        "wiki2": "gintama",
        "page2": "Gintoki Sakata",
        "mode": "classic",
    },
    {
        "civil": "Hiei",
        "undercover": "Vegeta",
        "universe1": "Yu Yu Hakusho",
        "universe2": "Dragon Ball",
        "archetype": "Petit guerrier féroce et fier",
        "wiki1": "yuyuhakusho",
        "page1": "Hiei",
        "wiki2": "dragonball",
        "page2": "Vegeta",
        "mode": "classic",
    },
    {
        "civil": "Yusuke Urameshi",
        "undercover": "Goku",
        "universe1": "Yu Yu Hakusho",
        "universe2": "Dragon Ball",
        "archetype": "Combattant qui devient plus fort au combat",
        "wiki1": "yuyuhakusho",
        "page1": "Yusuke Urameshi",
        "wiki2": "dragonball",
        "page2": "Goku",
        "mode": "classic",
    },
    {
        "civil": "Kagome Higurashi",
        "undercover": "Usagi Tsukino",
        "universe1": "Inuyasha",
        "universe2": "Sailor Moon",
        "archetype": "Fille ordinaire projetée dans un monde magique",
        "wiki1": "inuyasha",
        "page1": "Kagome Higurashi",
        "wiki2": "sailormoon",
        "page2": "Usagi Tsukino",
        "mode": "classic",
    },
    {
        "civil": "Sesshōmaru",
        "undercover": "Byakuya Kuchiki",
        "universe1": "Inuyasha",
        "universe2": "Bleach",
        "archetype": "Guerrier aristocratique froid",
        "wiki1": "inuyasha",
        "page1": "Sesshōmaru",
        "wiki2": "bleach",
        "page2": "Byakuya Kuchiki",
        "mode": "classic",
    },
    {
        "civil": "Miroku",
        "undercover": "Jiraiya",
        "universe1": "Inuyasha",
        "universe2": "Naruto",
        "archetype": "Pervers mais puissant mentor",
        "wiki1": "inuyasha",
        "page1": "Miroku",
        "wiki2": "naruto",
        "page2": "Jiraiya",
        "mode": "classic",
    },
    {
        "civil": "Spike Spiegel",
        "undercover": "Himura Kenshin",
        "universe1": "Cowboy Bebop",
        "universe2": "Rurouni Kenshin",
        "archetype": "Homme essayant d'échapper à un passé violent",
        "wiki1": "cowboy-bebop",
        "page1": "Spike Spiegel",
        "wiki2": "rurounikenshin",
        "page2": "Himura Kenshin",
        "mode": "classic",
    },
    {
        "civil": "Char Aznable",
        "undercover": "Griffith",
        "universe1": "Gundam",
        "universe2": "Berserk",
        "archetype": "Antagoniste charismatique masqué",
        "wiki1": "gundam",
        "page1": "Char Aznable",
        "wiki2": "berserk",
        "page2": "Griffith",
        "mode": "classic",
    },
    {
        "civil": "Pegasus Seiya",
        "undercover": "Rock Lee",
        "universe1": "Saint Seiya",
        "universe2": "Naruto",
        "archetype": "Combattant qui gagne par la force de volonté",
        "wiki1": "saintseiya",
        "page1": "Pegasus Seiya",
        "wiki2": "naruto",
        "page2": "Rock Lee",
        "mode": "classic",
    },
    {
        "civil": "Hanamichi Sakuragi",
        "undercover": "Asta",
        "universe1": "Slam Dunk",
        "universe2": "Black Clover",
        "archetype": "Délinquant roux bruyant avec un talent caché",
        "wiki1": "slamdunk",
        "page1": "Hanamichi Sakuragi",
        "wiki2": "blackclover",
        "page2": "Asta",
        "mode": "classic",
    },
    {
        "civil": "Shinomori Aoshi",
        "undercover": "Sasuke Uchiha",
        "universe1": "Rurouni Kenshin",
        "universe2": "Naruto",
        "archetype": "Rival obsédé par être le plus fort",
        "wiki1": "rurounikenshin",
        "page1": "Shinomori Aoshi",
        "wiki2": "naruto",
        "page2": "Sasuke Uchiha",
        "mode": "classic",
    },

    # =========================================================================
    # MODE SEINEN 🖤 - mature, dark themes
    # =========================================================================
    {
        "civil": "Thorfinn",
        "undercover": "Guts",
        "universe1": "Vinland Saga",
        "universe2": "Berserk",
        "archetype": "Guerrier cherchant vengeance puis rédemption",
        "wiki1": "vinland-saga",
        "page1": "Thorfinn",
        "wiki2": "berserk",
        "page2": "Guts",
        "mode": "seinen",
    },
    {
        "civil": "Johan Liebert",
        "undercover": "Light Yagami",
        "universe1": "Monster",
        "universe2": "Death Note",
        "archetype": "Beau sociopathe manipulant tout le monde",
        "wiki1": "monster",
        "page1": "Johan Liebert",
        "wiki2": "deathnote",
        "page2": "Light Yagami",
        "mode": "seinen",
    },
    {
        "civil": "Miyamoto Musashi",
        "undercover": "Himura Kenshin",
        "universe1": "Vagabond",
        "universe2": "Rurouni Kenshin",
        "archetype": "Épéiste légendaire cherchant un sens",
        "wiki1": "vagabond",
        "page1": "Miyamoto Musashi",
        "wiki2": "rurounikenshin",
        "page2": "Himura Kenshin",
        "mode": "seinen",
    },
    {
        "civil": "Akane Tsunemori",
        "undercover": "Motoko Kusanagi",
        "universe1": "Psycho-Pass",
        "universe2": "Ghost in the Shell",
        "archetype": "Femme agent de la loi questionnant le système",
        "wiki1": "psycho-pass",
        "page1": "Akane Tsunemori",
        "wiki2": "ghost-in-the-shell",
        "page2": "Motoko Kusanagi",
        "mode": "seinen",
    },
    {
        "civil": "Shinichi Izumi",
        "undercover": "Ken Kaneki",
        "universe1": "Parasyte",
        "universe2": "Tokyo Ghoul",
        "archetype": "Humain fusionné avec un monstre",
        "wiki1": "kiseijuu",
        "page1": "Shinichi Izumi",
        "wiki2": "tokyoghoul",
        "page2": "Ken Kaneki",
        "mode": "seinen",
    },
    {
        "civil": "Thorfinn",
        "undercover": "Eren Yeager",
        "universe1": "Vinland Saga",
        "universe2": "Attack on Titan",
        "archetype": "Garçon consumé par la vengeance",
        "wiki1": "vinland-saga",
        "page1": "Thorfinn",
        "wiki2": "attackontitan",
        "page2": "Eren Yeager",
        "mode": "seinen",
    },
    {
        "civil": "Askeladd",
        "undercover": "Erwin Smith",
        "universe1": "Vinland Saga",
        "universe2": "Attack on Titan",
        "archetype": "Leader charismatique utilisant les autres comme pions",
        "wiki1": "vinland-saga",
        "page1": "Askeladd",
        "wiki2": "attackontitan",
        "page2": "Erwin Smith",
        "mode": "seinen",
    },
    {
        "civil": "Johan Liebert",
        "undercover": "Sosuke Aizen",
        "universe1": "Monster",
        "universe2": "Bleach",
        "archetype": "Vilain si intelligent que personne ne sait qu'il est le vilain",
        "wiki1": "monster",
        "page1": "Johan Liebert",
        "wiki2": "bleach",
        "page2": "Sosuke Aizen",
        "mode": "seinen",
    },
    {
        "civil": "Shogo Makishima",
        "undercover": "Johan Liebert",
        "universe1": "Psycho-Pass",
        "universe2": "Monster",
        "archetype": "Beau vilain philosophe",
        "wiki1": "psycho-pass",
        "page1": "Shogo Makishima",
        "wiki2": "monster",
        "page2": "Johan Liebert",
        "mode": "seinen",
    },
    {
        "civil": "Motoko Kusanagi",
        "undercover": "Mikasa Ackerman",
        "universe1": "Ghost in the Shell",
        "universe2": "Attack on Titan",
        "archetype": "Guerrière presque surhumaine",
        "wiki1": "ghost-in-the-shell",
        "page1": "Motoko Kusanagi",
        "wiki2": "attackontitan",
        "page2": "Mikasa Ackerman",
        "mode": "seinen",
    },
    {
        "civil": "Canute",
        "undercover": "Lelouch Lamperouge",
        "universe1": "Vinland Saga",
        "universe2": "Code Geass",
        "archetype": "Prince faible devenu roi impitoyable",
        "wiki1": "vinland-saga",
        "page1": "Canute",
        "wiki2": "codegeass",
        "page2": "Lelouch Lamperouge",
        "mode": "seinen",
    },
    {
        "civil": "Shinichi Izumi",
        "undercover": "Denji",
        "universe1": "Parasyte",
        "universe2": "Chainsaw Man",
        "archetype": "Adolescent lié à une entité inhumaine",
        "wiki1": "kiseijuu",
        "page1": "Shinichi Izumi",
        "wiki2": "chainsawman",
        "page2": "Denji",
        "mode": "seinen",
    },
    {
        "civil": "Griffith",
        "undercover": "Johan Liebert",
        "universe1": "Berserk",
        "universe2": "Monster",
        "archetype": "Beau vilain qui détruit tout",
        "wiki1": "berserk",
        "page1": "Griffith",
        "wiki2": "monster",
        "page2": "Johan Liebert",
        "mode": "seinen",
    },
    {
        "civil": "Revy",
        "undercover": "Mikasa Ackerman",
        "universe1": "Black Lagoon",
        "universe2": "Attack on Titan",
        "archetype": "Femme armée avec un traumatisme",
        "wiki1": "black-lagoon",
        "page1": "Revy",
        "wiki2": "attackontitan",
        "page2": "Mikasa Ackerman",
        "mode": "seinen",
    },
    {
        "civil": "Guts",
        "undercover": "Thorfinn",
        "universe1": "Berserk",
        "universe2": "Vinland Saga",
        "archetype": "Guerrier enragé apprenant la paix",
        "wiki1": "berserk",
        "page1": "Guts",
        "wiki2": "vinland-saga",
        "page2": "Thorfinn",
        "mode": "seinen",
    },
]


# =============================================================================
# DISPLAY NAMES - maps wiki page identifiers to short display names
# =============================================================================

DISPLAY_NAMES = {
    # Naruto
    "Kakashi Hatake": "Kakashi",
    "Naruto Uzumaki": "Naruto",
    "Sasuke Uchiha": "Sasuke",
    "Itachi Uchiha": "Itachi",
    "Jiraiya": "Jiraiya",
    "Orochimaru": "Orochimaru",
    "Sakura Haruno": "Sakura",
    "Tsunade": "Tsunade",
    "Gaara": "Gaara",
    "Madara Uchiha": "Madara",
    "Hashirama Senju": "Hashirama",
    "Obito Uchiha": "Obito",
    "Minato Namikaze": "Minato",
    "Shikamaru Nara": "Shikamaru",
    "Neji Hyūga": "Neji",
    "Hinata Hyūga": "Hinata",
    "Rock Lee": "Rock Lee",
    "Nagato": "Pain",
    "Konan": "Konan",
    "Kurama": "Kurama",
    "Kaguya Ōtsutsuki": "Kaguya",

    # Dragon Ball
    "Goku": "Goku",
    "Vegeta": "Vegeta",
    "Gohan": "Gohan",
    "Trunks": "Trunks",
    "Frieza": "Frieza",
    "Cell": "Cell",
    "Piccolo": "Piccolo",
    "Broly (DBS)": "Broly",
    "Beerus": "Beerus",
    "Whis": "Whis",
    "Master Roshi": "Muten Roshi",
    "Zeno": "Zeno",
    "Android 18": "Android 18",
    "Bulma": "Bulma",

    # One Piece
    "Monkey D. Luffy": "Luffy",
    "Roronoa Zoro": "Zoro",
    "Sanji": "Sanji",
    "Nami": "Nami",
    "Nico Robin": "Robin",
    "Portgas D. Ace": "Ace",
    "Sabo": "Sabo",
    "Shanks": "Shanks",
    "Edward Newgate": "Barbe Blanche",
    "Silvers Rayleigh": "Rayleigh",
    "Donquixote Doflamingo": "Doflamingo",
    "Crocodile": "Crocodile",
    "Dracule Mihawk": "Mihawk",
    "Marshall D. Teach": "Barbe Noire",
    "Gol D. Roger": "Roger",
    "Trafalgar D. Water Law": "Law",
    "Donquixote Rosinante": "Corazon",
    "Charlotte Linlin": "Big Mom",

    # Bleach
    "Ichigo Kurosaki": "Ichigo",
    "Rukia Kuchiki": "Rukia",
    "Byakuya Kuchiki": "Byakuya",
    "Sousuke Aizen": "Aizen",
    "Kisuke Urahara": "Urahara",
    "Grimmjow Jaegerjaquez": "Grimmjow",
    "Tōshirō Hitsugaya": "Toshiro",
    "Rangiku Matsumoto": "Rangiku",
    "Yoruichi Shihōin": "Yoruichi",
    "Retsu Unohana": "Unohana",
    "Yhwach": "Yhwach",

    # Attack on Titan
    "Eren Yeager": "Eren",
    "Mikasa Ackerman": "Mikasa",
    "Levi Ackerman": "Levi",
    "Erwin Smith (Anime)": "Erwin",
    "Reiner Braun (Anime)": "Reiner",
    "Annie Leonhart (Anime)": "Annie",
    "Armin Arlert": "Armin",
    "Zeke Yeager": "Zeke",
    "Ymir Fritz (Anime)": "Ymir Fritz",
    "Marco Bott": "Marco",
    "Willy Tybur (Anime)": "Willy Tybur",

    # My Hero Academia
    "Izuku Midoriya": "Deku",
    "Katsuki Bakugo": "Bakugo",
    "Shoto Todoroki": "Todoroki",
    "Toshinori Yagi": "All Might",
    "Enji Todoroki": "Endeavor",
    "Rumi Usagiyama": "Mirko",

    # Jujutsu Kaisen
    "Satoru Gojo": "Gojo",
    "Sukuna": "Sukuna",
    "Yuji Itadori": "Yuji",
    "Megumi Fushiguro": "Megumi",
    "Toji Fushiguro": "Toji",
    "Suguru Geto": "Geto",
    "Nobara Kugisaki": "Nobara",
    "Maki Zenin": "Maki",
    "Aoi Todo": "Todo",

    # Demon Slayer
    "Tanjiro Kamado": "Tanjiro",
    "Nezuko Kamado": "Nezuko",
    "Zenitsu Agatsuma": "Zenitsu",
    "Inosuke Hashibira": "Inosuke",
    "Muzan Kibutsuji": "Muzan",
    "Tamayo": "Tamayo",
    "Giyu Tomioka": "Giyu",
    "Sanemi Shinazugawa": "Sanemi",

    # Death Note
    "Light Yagami": "Light",
    "L (character)": "L",
    "Ryuk": "Ryuk",
    "Misa Amane": "Misa",
    "Rem": "Rem",
    "Near": "Near",
    "Mello": "Mello",

    # Hunter x Hunter
    "Gon Freecss": "Gon",
    "Killua Zoldyck": "Killua",
    "Kurapika": "Kurapika",
    "Hisoka Morow": "Hisoka",
    "Chrollo Lucilfer": "Chrollo",
    "Meruem": "Meruem",
    "Isaac Netero": "Netero",
    "Biscuit Krueger": "Biscuit",
    "Kite": "Kite",
    "Alluka Zoldyck": "Alluka",
    "Phantom Troupe": "Brigade Fantôme",

    # Fullmetal Alchemist
    "Edward Elric": "Edward",
    "Alphonse Elric": "Alphonse",
    "Roy Mustang": "Mustang",
    "Riza Hawkeye": "Riza",
    "Maes Hughes": "Hughes",
    "Scar": "Scar",
    "Solf J. Kimblee": "Kimblee",
    "Van Hohenheim": "Hohenheim",
    "Father": "Father",
    "King Bradley": "King Bradley",
    "Shou Tucker": "Shou Tucker",
    "Winry Rockbell": "Winry",
    "Truth": "Truth",

    # Code Geass
    "Lelouch vi Britannia": "Lelouch",
    "Charles zi Britannia": "Charles",
    "Cornelia li Britannia": "Cornelia",

    # Tokyo Ghoul
    "Ken Kaneki": "Kaneki",

    # Chainsaw Man
    "Denji": "Denji",
    "Makima": "Makima",
    "Power": "Power",
    "Pochita": "Pochita",

    # One Punch Man
    "Saitama": "Saitama",

    # Black Clover
    "Asta": "Asta",

    # Fairy Tail
    "Natsu Dragneel": "Natsu",
    "Erza Scarlet": "Erza",
    "Gildarts Clive": "Gildarts",

    # Mob Psycho 100
    "Shigeo Kageyama": "Mob",

    # Berserk
    "Guts": "Guts",
    "Griffith": "Griffith",
    "Casca": "Casca",

    # Dr. Stone
    "Senku Ishigami": "Senku",

    # Promised Neverland
    "Ray": "Ray",

    # Evangelion
    "Shinji Ikari": "Shinji",

    # Akira
    "Tetsuo Shima": "Tetsuo",

    # Yu Yu Hakusho
    "Genkai": "Genkai",
    "Hiei": "Hiei",

    # Seven Deadly Sins
    "Meliodas": "Meliodas",

    # Gurren Lagann
    "Simon": "Simon",

    # Avatar
    "Iroh": "Iroh",

    # Konosuba
    "Aqua": "Aqua",

    # JoJo
    "Dio Brando": "Dio",

    # Slime
    "Rimuru Tempest": "Rimuru",

    # Assassination Classroom
    "Korosensei": "Koro-sensei",

    # Akame ga Kill
    "Esdeath": "Esdeath",

    # Gintama
    "Gintoki Sakata": "Gintoki",

    # --- MODE SHŌJO ---
    # Sailor Moon
    "Usagi Tsukino": "Usagi",
    "Rei Hino": "Rei",
    "Hotaru Tomoe": "Hotaru",
    "Chibiusa": "Chibiusa",

    # Cardcaptor Sakura
    "Sakura Kinomoto": "Sakura",
    "Tomoyo Daidouji": "Tomoyo",
    "Syaoran Li": "Syaoran",

    # Fruits Basket
    "Tohru Honda": "Tohru",
    "Kyo Sohma": "Kyo",
    "Yuki Sohma": "Yuki",
    "Momiji Sohma": "Momiji",
    "Akito Sohma": "Akito",

    # Ouran High School Host Club
    "Tamaki Suoh": "Tamaki",
    "Haruhi Fujioka": "Haruhi",
    "Mitsukuni Haninozuka": "Honey",

    # Kimi ni Todoke
    "Sawako Kuronuma": "Sawako",

    # Clannad
    "Nagisa Furukawa": "Nagisa",
    "Tomoya Okazaki": "Tomoya",

    # Violet Evergarden
    "Violet Evergarden": "Violet",

    # Your Lie in April
    "Kaori Miyazono": "Kaori",
    "Kousei Arima": "Kousei",

    # Toradora
    "Taiga Aisaka": "Taiga",

    # Evangelion (shojo crossover)
    "Rei Ayanami": "Rei",
    "Asuka Langley Soryu": "Asuka",

    # Puella Magi Madoka Magica
    "Madoka Kaname": "Madoka",
    "Homura Akemi": "Homura",

    # Full Moon wo Sagashite
    "Mitsuki Koyama": "Mitsuki",

    # Magical Girl Lyrical Nanoha
    "Nanoha Takamachi": "Nanoha",

    # Maid Sama
    "Misaki Ayuzawa": "Misaki",
    "Takumi Usui": "Usui",

    # Black Butler
    "Ciel Phantomhive": "Ciel",

    # Code Geass (shojo crossover)
    "Nunnally vi Britannia": "Nunnally",

    # --- MODE ISEKAI ---
    # Re:Zero
    "Subaru Natsuki": "Subaru",
    "Emilia": "Emilia",
    "Rem": "Rem",
    "Reinhard van Astrea": "Reinhard",
    "Roswaal L Mathers": "Roswaal",
    "Echidna": "Echidna",

    # Sword Art Online
    "Kirito": "Kirito",
    "Asuna": "Asuna",

    # Overlord
    "Ainz Ooal Gown": "Ainz",
    "Albedo": "Albedo",
    "Shalltear Bloodfallen": "Shalltear",

    # Slime
    "Rimuru Tempest": "Rimuru",

    # KonoSuba
    "Kazuma Satou": "Kazuma",
    "Megumin": "Megumin",
    "Darkness": "Darkness",
    "Wiz": "Wiz",

    # Mushoku Tensei
    "Rudeus Greyrat": "Rudeus",

    # Shield Hero
    "Naofumi Iwatani": "Naofumi",
    "Raphtalia": "Raphtalia",

    # No Game No Life
    "Sora": "Sora",
    "Shiro": "Shiro",

    # How Not to Summon a Demon Lord
    "Diablo": "Diablo",

    # --- MODE CLASSIQUE ---
    # Saint Seiya
    "Pegasus Seiya": "Seiya",

    # Slam Dunk
    "Hanamichi Sakuragi": "Sakuragi",

    # Inuyasha
    "Inuyasha": "Inuyasha",
    "Kagome Higurashi": "Kagome",
    "Sesshōmaru": "Sesshōmaru",
    "Miroku": "Miroku",

    # Hokuto no Ken
    "Kenshiro": "Kenshiro",

    # Ranma ½
    "Ranma Saotome": "Ranma",

    # Yu-Gi-Oh
    "Yugi Mutou": "Yugi",

    # Captain Tsubasa
    "Tsubasa Ozora": "Tsubasa",

    # Rurouni Kenshin
    "Himura Kenshin": "Kenshin",
    "Shinomori Aoshi": "Aoshi",

    # Trigun
    "Vash the Stampede": "Vash",

    # Cowboy Bebop
    "Spike Spiegel": "Spike",

    # Gundam
    "Char Aznable": "Char",

    # Yu Yu Hakusho
    "Yusuke Urameshi": "Yusuke",

    # --- MODE SEINEN ---
    # Vinland Saga
    "Thorfinn": "Thorfinn",
    "Askeladd": "Askeladd",
    "Canute": "Canute",

    # Monster
    "Johan Liebert": "Johan",

    # Vagabond
    "Miyamoto Musashi": "Musashi",

    # Psycho-Pass
    "Akane Tsunemori": "Akane",
    "Shogo Makishima": "Makishima",

    # Ghost in the Shell
    "Motoko Kusanagi": "Motoko",

    # Parasyte
    "Shinichi Izumi": "Shinichi",

    # Black Lagoon
    "Revy": "Revy",
}
