# -*- coding: utf-8 -*-
"""LELOX MENTEUR — base de questions (150)"""
QUESTIONS = [
    # ===== CULTURE GÉNÉRALE (30) =====
    {"id":"cg001","question":"Quelle est la vraie signification du mot 'Petrichor' ?","answer":"L'odeur de la pluie sur la terre sèche","category":"Culture Générale","difficulty":"medium","fun_fact":"Du grec petra (pierre) et ichor (fluide des dieux)"},
    {"id":"cg002","question":"Combien de cœurs possède une pieuvre ?","answer":"3 cœurs","category":"Culture Générale","difficulty":"medium","fun_fact":"Un cœur systémique et deux cœurs branchiaux"},
    {"id":"cg003","question":"Quel pays a inventé les frites ?","answer":"La Belgique","category":"Culture Générale","difficulty":"easy","fun_fact":"Les soldats américains de la WWI les ont découvertes en Belgique"},
    {"id":"cg004","question":"Quelle est la seule lettre absente du tableau périodique ?","answer":"La lettre J","category":"Culture Générale","difficulty":"hard","fun_fact":"Toutes les autres apparaissent dans au moins un symbole"},
    {"id":"cg005","question":"Combien de muscles utilise-t-on pour sourire ?","answer":"12 muscles","category":"Culture Générale","difficulty":"easy","fun_fact":"Vs 11 muscles pour froncer les sourcils"},
    {"id":"cg006","question":"Quelle est la vitesse d'un éternuement ?","answer":"Environ 160 km/h","category":"Culture Générale","difficulty":"medium","fun_fact":"Les gouttelettes peuvent parcourir jusqu'à 8 mètres"},
    {"id":"cg007","question":"Combien de fois par jour rit un adulte en moyenne ?","answer":"17 fois","category":"Culture Générale","difficulty":"easy","fun_fact":"Un enfant rit en moyenne 300 fois par jour"},
    {"id":"cg008","question":"Quelle est la durée de vie d'un globule rouge ?","answer":"120 jours","category":"Culture Générale","difficulty":"medium","fun_fact":"Le corps en produit 2 millions par seconde"},
    {"id":"cg009","question":"Quel est l'animal terrestre le plus rapide ?","answer":"Le guépard (110 km/h)","category":"Culture Générale","difficulty":"easy","fun_fact":"Il atteint 100 km/h en 3 secondes"},
    {"id":"cg010","question":"Combien de langues sont parlées dans le monde ?","answer":"Environ 7000","category":"Culture Générale","difficulty":"hard","fun_fact":"50% de l'humanité parle seulement 23 langues"},
    {"id":"cg011","question":"Quelle est la profondeur maximale de l'océan ?","answer":"11034 mètres (fosse des Mariannes)","category":"Culture Générale","difficulty":"medium","fun_fact":"Plus profond que l'Everest est haut"},
    {"id":"cg012","question":"Combien d'os a un nouveau-né ?","answer":"270 os","category":"Culture Générale","difficulty":"hard","fun_fact":"Les adultes en ont 206 — certains fusionnent"},
    {"id":"cg013","question":"Quelle planète a une journée plus longue que son année ?","answer":"Vénus","category":"Culture Générale","difficulty":"medium","fun_fact":"Journée: 243 jours terrestres, année: 225"},
    {"id":"cg014","question":"Quel fruit contient le plus de vitamine C ?","answer":"La goyave","category":"Culture Générale","difficulty":"medium","fun_fact":"Le kiwi contient 2x plus de vitamine C que l'orange"},
    {"id":"cg015","question":"Combien de dents a un adulte humain ?","answer":"32 dents","category":"Culture Générale","difficulty":"easy","fun_fact":"En comptant les dents de sagesse"},
    {"id":"cg016","question":"Quelle est la capitale de l'Australie ?","answer":"Canberra","category":"Culture Générale","difficulty":"medium","fun_fact":"Pas Sydney comme on le pense souvent"},
    {"id":"cg017","question":"Combien de pays compte officiellement l'ONU ?","answer":"193 pays","category":"Culture Générale","difficulty":"hard","fun_fact":"Le dernier admis est le Sud Soudan en 2011"},
    {"id":"cg018","question":"Quel est le plus grand désert du monde ?","answer":"L'Antarctique","category":"Culture Générale","difficulty":"hard","fun_fact":"Un désert se définit par les précipitations, pas la chaleur"},
    {"id":"cg019","question":"Quelle est la couleur officielle du deuil en Chine ?","answer":"Le blanc","category":"Culture Générale","difficulty":"medium","fun_fact":"Le rouge symbolise le bonheur en Chine"},
    {"id":"cg020","question":"Quel est l'organe humain qui se régénère le plus vite ?","answer":"Le foie","category":"Culture Générale","difficulty":"medium","fun_fact":"Il peut repousser à partir de 25% de son volume"},
    {"id":"cg021","question":"Combien de touches a un piano standard ?","answer":"88 touches","category":"Culture Générale","difficulty":"medium","fun_fact":"52 blanches et 36 noires"},
    {"id":"cg022","question":"Quel pays consomme le plus de chocolat par habitant ?","answer":"La Suisse (~9 kg/an)","category":"Culture Générale","difficulty":"medium","fun_fact":"Devant l'Allemagne et l'Irlande"},
    {"id":"cg023","question":"Combien de continents y a-t-il ?","answer":"7 continents","category":"Culture Générale","difficulty":"easy","fun_fact":"Selon le modèle nord-américain — 5 ou 6 selon d'autres"},
    {"id":"cg024","question":"Quel est l'instrument le plus difficile à maîtriser ?","answer":"Le violon (selon la plupart des experts)","category":"Culture Générale","difficulty":"hard","fun_fact":"Devant le hautbois, la harpe, l'orgue"},
    {"id":"cg025","question":"Combien d'éléments contient le tableau périodique ?","answer":"118 éléments","category":"Culture Générale","difficulty":"medium","fun_fact":"Le dernier découvert est l'oganesson en 2002"},
    {"id":"cg026","question":"Quelle est la longueur de la Grande Muraille de Chine ?","answer":"21196 km","category":"Culture Générale","difficulty":"hard","fun_fact":"Avec ses ramifications — la partie principale fait environ 8850 km"},
    {"id":"cg027","question":"Combien de cellules nerveuses a un cerveau humain ?","answer":"Environ 86 milliards","category":"Culture Générale","difficulty":"hard","fun_fact":"On a longtemps cru qu'il y en avait 100 milliards"},
    {"id":"cg028","question":"Quel est le pays le plus peuplé du monde ?","answer":"L'Inde","category":"Culture Générale","difficulty":"easy","fun_fact":"L'Inde a dépassé la Chine en 2023"},
    {"id":"cg029","question":"Quelle est la durée moyenne d'un rêve ?","answer":"De 5 à 20 minutes","category":"Culture Générale","difficulty":"medium","fun_fact":"On fait 4 à 6 rêves par nuit en phase REM"},
    {"id":"cg030","question":"Combien d'années dure la lumière du Soleil pour atteindre la Terre ?","answer":"8 minutes 20 secondes","category":"Culture Générale","difficulty":"medium","fun_fact":"On voit le Soleil tel qu'il était il y a 8 minutes"},

    # ===== SCIENCES BIZARRES (25) =====
    {"id":"sc001","question":"Combien de temps un humain reste conscient dans l'espace sans combinaison ?","answer":"Environ 15 secondes","category":"Sciences Bizarres","difficulty":"hard","fun_fact":"La mort surviendrait en 1-2 minutes"},
    {"id":"sc002","question":"Quelle est la température au centre de la Terre ?","answer":"Environ 6000°C","category":"Sciences Bizarres","difficulty":"medium","fun_fact":"Même température que la surface du Soleil"},
    {"id":"sc003","question":"Combien de bactéries vivent sur le corps humain ?","answer":"Environ 38 000 milliards","category":"Sciences Bizarres","difficulty":"hard","fun_fact":"Presque autant que de cellules humaines"},
    {"id":"sc004","question":"Quel métal est liquide à température ambiante (hormis le mercure) ?","answer":"Le gallium (fond à 29°C)","category":"Sciences Bizarres","difficulty":"hard","fun_fact":"Il fond dans la main"},
    {"id":"sc005","question":"Quelle est la chose la plus froide de l'univers connu ?","answer":"La nébuleuse du Boomerang (-272°C)","category":"Sciences Bizarres","difficulty":"hard","fun_fact":"Plus froid que le fond diffus cosmologique"},
    {"id":"sc006","question":"Combien de fois la lumière fait-elle le tour de la Terre par seconde ?","answer":"7,5 fois","category":"Sciences Bizarres","difficulty":"medium","fun_fact":"299792 km/s contre 40075 km de circonférence"},
    {"id":"sc007","question":"Quel animal ne dort jamais comme nous ?","answer":"Le dauphin (un hémisphère à la fois)","category":"Sciences Bizarres","difficulty":"hard","fun_fact":"Cela leur permet de remonter respirer"},
    {"id":"sc008","question":"À quelle vitesse pousse un ongle humain par mois ?","answer":"Environ 3,5 mm","category":"Sciences Bizarres","difficulty":"medium","fun_fact":"Plus vite l'été et sur la main dominante"},
    {"id":"sc009","question":"Quelle couleur l'œil humain perçoit-il le mieux ?","answer":"Le vert-jaune (555 nm)","category":"Sciences Bizarres","difficulty":"hard","fun_fact":"D'où les gilets de sécurité jaune-vert"},
    {"id":"sc010","question":"Combien de tonnes de météorites tombent sur Terre par jour ?","answer":"Environ 50 tonnes","category":"Sciences Bizarres","difficulty":"hard","fun_fact":"La plupart en poussière dans l'atmosphère"},
    {"id":"sc011","question":"Quelle est la pression au fond de la fosse des Mariannes ?","answer":"Plus de 1000 atmosphères","category":"Sciences Bizarres","difficulty":"hard","fun_fact":"Soit 8 tonnes par centimètre carré"},
    {"id":"sc012","question":"De quoi sont faites les empreintes digitales ?","answer":"De crêtes papillaires de la peau","category":"Sciences Bizarres","difficulty":"medium","fun_fact":"Elles se forment in utero entre la 10e et 19e semaine"},
    {"id":"sc013","question":"Quelle est la durée d'un jour sur Mercure ?","answer":"176 jours terrestres","category":"Sciences Bizarres","difficulty":"hard","fun_fact":"Plus long que son année (88 jours)"},
    {"id":"sc014","question":"Combien d'eau y a-t-il dans le corps humain ?","answer":"Environ 60%","category":"Sciences Bizarres","difficulty":"easy","fun_fact":"Le cerveau contient 73% d'eau"},
    {"id":"sc015","question":"Quel est l'animal le plus venimeux au monde ?","answer":"La méduse-boîte","category":"Sciences Bizarres","difficulty":"medium","fun_fact":"Son venin peut tuer un humain en 3 minutes"},
    {"id":"sc016","question":"Combien y a-t-il de planètes naines dans le système solaire ?","answer":"5 reconnues officiellement","category":"Sciences Bizarres","difficulty":"hard","fun_fact":"Pluton, Cérès, Eris, Hauméa, Makémaké"},
    {"id":"sc017","question":"Quelle est la durée de vie d'une libellule ?","answer":"Environ 6 mois (forme adulte: 4 semaines)","category":"Sciences Bizarres","difficulty":"medium","fun_fact":"Elle passe la majeure partie de sa vie en larve"},
    {"id":"sc018","question":"Quel pourcentage de notre ADN partage-t-on avec une banane ?","answer":"Environ 60%","category":"Sciences Bizarres","difficulty":"medium","fun_fact":"Et 98,8% avec un chimpanzé"},
    {"id":"sc019","question":"Combien de fois bat un cœur humain en une vie ?","answer":"Environ 2,5 milliards de fois","category":"Sciences Bizarres","difficulty":"hard","fun_fact":"Sur une espérance de vie de 80 ans"},
    {"id":"sc020","question":"Quelle est la vitesse du son dans l'eau ?","answer":"Environ 1500 m/s","category":"Sciences Bizarres","difficulty":"medium","fun_fact":"4,5x plus vite que dans l'air"},
    {"id":"sc021","question":"Combien d'espèces vivantes ont été identifiées ?","answer":"Environ 1,5 million","category":"Sciences Bizarres","difficulty":"hard","fun_fact":"Estimation totale: 8,7 millions"},
    {"id":"sc022","question":"Quelle planète a les vents les plus rapides ?","answer":"Neptune (jusqu'à 2100 km/h)","category":"Sciences Bizarres","difficulty":"hard","fun_fact":"Plus rapide que la vitesse du son"},
    {"id":"sc023","question":"Quelle est la masse de la Voie Lactée ?","answer":"Environ 1500 milliards de masses solaires","category":"Sciences Bizarres","difficulty":"hard","fun_fact":"En comptant la matière noire"},
    {"id":"sc024","question":"Combien de globules rouges produit-on par seconde ?","answer":"Environ 2 millions","category":"Sciences Bizarres","difficulty":"hard","fun_fact":"Soit 173 milliards par jour"},
    {"id":"sc025","question":"À quelle température l'eau bout-elle au sommet de l'Everest ?","answer":"Environ 70°C","category":"Sciences Bizarres","difficulty":"medium","fun_fact":"À cause de la basse pression atmosphérique"},

    # ===== HISTOIRE IMPROBABLE (25) =====
    {"id":"hi001","question":"Quelle guerre a duré seulement 38 minutes ?","answer":"La guerre Anglo-Zanzibar (1896)","category":"Histoire Improbable","difficulty":"hard","fun_fact":"Zanzibar capitula à 9h40"},
    {"id":"hi002","question":"Quel président américain a obtenu un brevet ?","answer":"Abraham Lincoln","category":"Histoire Improbable","difficulty":"medium","fun_fact":"Brevet No. 6469 en 1849, pour soulever des bateaux échoués"},
    {"id":"hi003","question":"Combien d'années a duré la construction de la cathédrale de Cologne ?","answer":"632 ans","category":"Histoire Improbable","difficulty":"medium","fun_fact":"De 1248 à 1880"},
    {"id":"hi004","question":"Dans quelle ville est-il interdit de mourir ?","answer":"Longyearbyen (Norvège)","category":"Histoire Improbable","difficulty":"medium","fun_fact":"Le sol gelé empêche la décomposition"},
    {"id":"hi005","question":"Quel empire a duré le plus longtemps ?","answer":"L'Empire byzantin (1123 ans)","category":"Histoire Improbable","difficulty":"hard","fun_fact":"De 330 à 1453"},
    {"id":"hi006","question":"Combien de fois le Brésil a-t-il gagné la Coupe du Monde ?","answer":"5 fois","category":"Histoire Improbable","difficulty":"easy","fun_fact":"1958, 1962, 1970, 1994, 2002"},
    {"id":"hi007","question":"Combien de personnes ont marché sur la Lune ?","answer":"12 personnes","category":"Histoire Improbable","difficulty":"medium","fun_fact":"De 1969 à 1972, missions Apollo 11 à 17"},
    {"id":"hi008","question":"Quel animal a tué le plus d'humains dans l'histoire ?","answer":"Le moustique","category":"Histoire Improbable","difficulty":"medium","fun_fact":"Plus de 50% de l'humanité l'a payé de sa vie"},
    {"id":"hi009","question":"En quelle année a eu lieu la première Coupe du Monde ?","answer":"1930","category":"Histoire Improbable","difficulty":"medium","fun_fact":"En Uruguay, gagnée par les Uruguayens"},
    {"id":"hi010","question":"Quel pharaon a régné le plus longtemps ?","answer":"Pépi II (94 ans)","category":"Histoire Improbable","difficulty":"hard","fun_fact":"Couronné à l'âge de 6 ans"},
    {"id":"hi011","question":"Quel pays a inventé les feux d'artifice ?","answer":"La Chine","category":"Histoire Improbable","difficulty":"easy","fun_fact":"Vers le VIIe siècle pendant la dynastie Tang"},
    {"id":"hi012","question":"Combien de républiques françaises y a-t-il eu ?","answer":"5 républiques","category":"Histoire Improbable","difficulty":"medium","fun_fact":"La Ve République date de 1958"},
    {"id":"hi013","question":"Quel monument a été construit en 7 ans ?","answer":"La Tour Eiffel (de 1887 à 1889)","category":"Histoire Improbable","difficulty":"medium","fun_fact":"En réalité 2 ans, 2 mois et 5 jours"},
    {"id":"hi014","question":"Quel pays a été le premier à accorder le droit de vote aux femmes ?","answer":"La Nouvelle-Zélande (1893)","category":"Histoire Improbable","difficulty":"hard","fun_fact":"La France: 1944"},
    {"id":"hi015","question":"Quel est le plus vieux royaume encore existant ?","answer":"Le Japon (660 av. J.-C.)","category":"Histoire Improbable","difficulty":"hard","fun_fact":"Selon la tradition, fondé par l'empereur Jinmu"},
    {"id":"hi016","question":"Combien d'années Cléopâtre a-t-elle vécu après les pyramides de Gizeh ?","answer":"Plus de 2000 ans après","category":"Histoire Improbable","difficulty":"hard","fun_fact":"Cléopâtre est plus proche de nous que des pyramides"},
    {"id":"hi017","question":"Quelle ville antique a été détruite par le Vésuve ?","answer":"Pompéi","category":"Histoire Improbable","difficulty":"easy","fun_fact":"Le 24 août 79 ap. J.-C."},
    {"id":"hi018","question":"Combien de fois Napoléon a-t-il été en exil ?","answer":"2 fois","category":"Histoire Improbable","difficulty":"medium","fun_fact":"Île d'Elbe en 1814 puis Sainte-Hélène en 1815"},
    {"id":"hi019","question":"Quelle est la plus ancienne université du monde ?","answer":"L'Université Al Quaraouiyine (859, Maroc)","category":"Histoire Improbable","difficulty":"hard","fun_fact":"Toujours en activité aujourd'hui"},
    {"id":"hi020","question":"Quel inventeur a déposé plus de 1000 brevets ?","answer":"Thomas Edison (1093)","category":"Histoire Improbable","difficulty":"medium","fun_fact":"Le record est tenu par Shunpei Yamazaki avec plus de 11000"},
    {"id":"hi021","question":"En quelle année est tombé le mur de Berlin ?","answer":"1989","category":"Histoire Improbable","difficulty":"easy","fun_fact":"Le 9 novembre, après 28 ans"},
    {"id":"hi022","question":"Combien d'ans dura la guerre de Cent Ans ?","answer":"116 ans","category":"Histoire Improbable","difficulty":"medium","fun_fact":"De 1337 à 1453"},
    {"id":"hi023","question":"Quel président américain a été assassiné en 1865 ?","answer":"Abraham Lincoln","category":"Histoire Improbable","difficulty":"easy","fun_fact":"Au théâtre Ford à Washington"},
    {"id":"hi024","question":"Quel est le plus vieux livre imprimé encore conservé ?","answer":"Le Sutra du Diamant (868)","category":"Histoire Improbable","difficulty":"hard","fun_fact":"Imprimé en Chine, conservé au British Museum"},
    {"id":"hi025","question":"En quelle année l'humain a-t-il atteint le pôle Sud ?","answer":"1911 (Amundsen)","category":"Histoire Improbable","difficulty":"medium","fun_fact":"Roald Amundsen battit Robert Scott de 5 semaines"},

    # ===== ANIME & CULTURE POP (25) =====
    {"id":"ac001","question":"Combien d'épisodes a One Piece au total ?","answer":"Plus de 1100 épisodes","category":"Anime & Culture Pop","difficulty":"easy","fun_fact":"Une des séries animées les plus longues"},
    {"id":"ac002","question":"Quel est le vrai nom de L dans Death Note ?","answer":"L Lawliet","category":"Anime & Culture Pop","difficulty":"medium","fun_fact":"Révélé dans le guide officiel"},
    {"id":"ac003","question":"Quel village est le foyer de Naruto ?","answer":"Konoha (le village caché des feuilles)","category":"Anime & Culture Pop","difficulty":"easy","fun_fact":"Inspiré du Japon féodal"},
    {"id":"ac004","question":"Quel est le jeu vidéo le plus vendu ?","answer":"Minecraft (~300 millions)","category":"Anime & Culture Pop","difficulty":"medium","fun_fact":"Devant Tetris et GTA V"},
    {"id":"ac005","question":"Quel film d'animation est le plus rentable ?","answer":"Le Roi Lion (2019)","category":"Anime & Culture Pop","difficulty":"medium","fun_fact":"1,66 milliard $ au box-office"},
    {"id":"ac006","question":"Combien de saisons a Dragon Ball Z ?","answer":"9 saisons","category":"Anime & Culture Pop","difficulty":"medium","fun_fact":"291 épisodes entre 1989 et 1996"},
    {"id":"ac007","question":"Quel Pokémon est le plus lourd ?","answer":"Primal Groudon (999 kg)","category":"Anime & Culture Pop","difficulty":"hard","fun_fact":"Cosmoem aussi pèse 999 kg malgré sa petite taille"},
    {"id":"ac008","question":"Dans quel anime apparaît le 'Kamehameha' ?","answer":"Dragon Ball","category":"Anime & Culture Pop","difficulty":"easy","fun_fact":"Nommé d'après le roi hawaïen Kamehameha I"},
    {"id":"ac009","question":"Quel est le manga le plus vendu de l'histoire ?","answer":"One Piece (>500 millions)","category":"Anime & Culture Pop","difficulty":"medium","fun_fact":"Devant Golgo 13 et Dragon Ball"},
    {"id":"ac010","question":"Quel studio a produit Le Voyage de Chihiro ?","answer":"Studio Ghibli","category":"Anime & Culture Pop","difficulty":"easy","fun_fact":"Réalisé par Hayao Miyazaki en 2001"},
    {"id":"ac011","question":"Combien de Pokémon existe-t-il dans la dernière génération ?","answer":"Plus de 1000","category":"Anime & Culture Pop","difficulty":"hard","fun_fact":"Génération 9 (Scarlet/Violet) a passé le cap"},
    {"id":"ac012","question":"Quel est le premier anime diffusé à la télé française ?","answer":"Goldorak (1978)","category":"Anime & Culture Pop","difficulty":"hard","fun_fact":"Sur Antenne 2 — un succès colossal"},
    {"id":"ac013","question":"Quel personnage de Marvel a été créé en 1962 ?","answer":"Spider-Man","category":"Anime & Culture Pop","difficulty":"medium","fun_fact":"Par Stan Lee et Steve Ditko"},
    {"id":"ac014","question":"Quel est le film de super-héros le plus rentable ?","answer":"Avengers: Endgame (2,79 mds $)","category":"Anime & Culture Pop","difficulty":"easy","fun_fact":"Détrôné par Avatar 2 globalement, mais toujours roi du genre"},
    {"id":"ac015","question":"Quel acteur a interprété le plus de fois James Bond ?","answer":"Roger Moore (7 films)","category":"Anime & Culture Pop","difficulty":"hard","fun_fact":"Devant Sean Connery (6) et Daniel Craig (5)"},
    {"id":"ac016","question":"Dans quel anime apparaît l'attaque 'Bankai' ?","answer":"Bleach","category":"Anime & Culture Pop","difficulty":"medium","fun_fact":"Forme libérée des Zanpakuto"},
    {"id":"ac017","question":"Quel est le rôle principal de Mark Hamill dans Star Wars ?","answer":"Luke Skywalker","category":"Anime & Culture Pop","difficulty":"easy","fun_fact":"Il a aussi interprété le Joker (voix)"},
    {"id":"ac018","question":"Quel anime tourne autour d'un cahier de la mort ?","answer":"Death Note","category":"Anime & Culture Pop","difficulty":"easy","fun_fact":"37 épisodes diffusés en 2006-2007"},
    {"id":"ac019","question":"Quel est l'acteur principal du Seigneur des Anneaux (Frodon) ?","answer":"Elijah Wood","category":"Anime & Culture Pop","difficulty":"medium","fun_fact":"Il avait 19 ans au début du tournage"},
    {"id":"ac020","question":"Quelle série Netflix a battu tous les records en 2021 ?","answer":"Squid Game","category":"Anime & Culture Pop","difficulty":"easy","fun_fact":"142 millions de foyers en 4 semaines"},
    {"id":"ac021","question":"Qui a créé le manga Dragon Ball ?","answer":"Akira Toriyama","category":"Anime & Culture Pop","difficulty":"medium","fun_fact":"Il a aussi créé Dr. Slump"},
    {"id":"ac022","question":"Quel jeu vidéo a inventé le concept du Battle Royale ?","answer":"PUBG (2017) — popularisé par Fortnite","category":"Anime & Culture Pop","difficulty":"medium","fun_fact":"Inspiré du film japonais Battle Royale"},
    {"id":"ac023","question":"Combien d'opus principaux compte la saga Final Fantasy ?","answer":"16 opus principaux","category":"Anime & Culture Pop","difficulty":"hard","fun_fact":"Sans compter les spin-offs et MMO"},
    {"id":"ac024","question":"Quel est le personnage principal de Hunter x Hunter ?","answer":"Gon Freecss","category":"Anime & Culture Pop","difficulty":"easy","fun_fact":"Il cherche son père Ging"},
    {"id":"ac025","question":"Quel film Pixar a coûté le plus cher à produire ?","answer":"Toy Story 4 (200 millions $)","category":"Anime & Culture Pop","difficulty":"hard","fun_fact":"Devant Cars 3 et Coco"},

    # ===== JEUX VIDÉO (20) =====
    {"id":"jv001","question":"Quel jeu a le plus de speedrunners actifs ?","answer":"Super Mario 64","category":"Jeux Vidéo","difficulty":"medium","fun_fact":"Suivi de Minecraft et Hollow Knight"},
    {"id":"jv002","question":"Combien de planètes y a-t-il dans No Man's Sky ?","answer":"18 quintillions","category":"Jeux Vidéo","difficulty":"hard","fun_fact":"Générées procéduralement"},
    {"id":"jv003","question":"Quel est le jeu le plus cher à développer ?","answer":"Star Citizen (>700 M$)","category":"Jeux Vidéo","difficulty":"hard","fun_fact":"En développement depuis 2012"},
    {"id":"jv004","question":"Combien de jeux Mario sont sortis ?","answer":"Plus de 200 jeux","category":"Jeux Vidéo","difficulty":"hard","fun_fact":"Plus que tout autre personnage de jeu vidéo"},
    {"id":"jv005","question":"Quel est le personnage de jeu vidéo le plus reconnu ?","answer":"Mario","category":"Jeux Vidéo","difficulty":"easy","fun_fact":"Plus reconnu que Mickey selon certaines études"},
    {"id":"jv006","question":"En quelle année est sorti le premier Pokémon ?","answer":"1996","category":"Jeux Vidéo","difficulty":"medium","fun_fact":"Versions Rouge et Verte au Japon"},
    {"id":"jv007","question":"Quel jeu a popularisé le Battle Royale ?","answer":"Fortnite (2017)","category":"Jeux Vidéo","difficulty":"easy","fun_fact":"Inspiré par PUBG sorti la même année"},
    {"id":"jv008","question":"Combien de pixels a une Game Boy classique ?","answer":"160 x 144 pixels","category":"Jeux Vidéo","difficulty":"hard","fun_fact":"En 4 nuances de gris... vert"},
    {"id":"jv009","question":"Quel est le jeu le plus joué sur Twitch ?","answer":"League of Legends","category":"Jeux Vidéo","difficulty":"medium","fun_fact":"Régulièrement en tête depuis 2014"},
    {"id":"jv010","question":"Quel jeu Nintendo est le plus vendu ?","answer":"Mario Kart 8 Deluxe (~57 millions)","category":"Jeux Vidéo","difficulty":"medium","fun_fact":"Sur Nintendo Switch"},
    {"id":"jv011","question":"Quel est le studio derrière The Witcher ?","answer":"CD Projekt Red","category":"Jeux Vidéo","difficulty":"easy","fun_fact":"Studio polonais fondé en 2002"},
    {"id":"jv012","question":"Quel jeu a inventé le concept de Souls-like ?","answer":"Demon's Souls (2009)","category":"Jeux Vidéo","difficulty":"medium","fun_fact":"De FromSoftware, suivi de Dark Souls en 2011"},
    {"id":"jv013","question":"Combien de notes différentes utilise Guitar Hero ?","answer":"5 notes (vert, rouge, jaune, bleu, orange)","category":"Jeux Vidéo","difficulty":"medium","fun_fact":"6 sur la guitare avec le bouton spécial"},
    {"id":"jv014","question":"Quel est le hit MMO de Blizzard sorti en 2004 ?","answer":"World of Warcraft","category":"Jeux Vidéo","difficulty":"easy","fun_fact":"Plus de 12 millions d'abonnés à son pic"},
    {"id":"jv015","question":"Quel jeu a battu le record du plus de joueurs en simultané sur Steam ?","answer":"Counter-Strike 2 / PUBG selon les périodes","category":"Jeux Vidéo","difficulty":"hard","fun_fact":"PUBG a atteint 3,2 millions en 2018"},
    {"id":"jv016","question":"Quel est le créateur de Mario ?","answer":"Shigeru Miyamoto","category":"Jeux Vidéo","difficulty":"medium","fun_fact":"Aussi créateur de Zelda et Donkey Kong"},
    {"id":"jv017","question":"Combien de plateformes ont été lancées par Sony pour la PlayStation ?","answer":"5 (PS1, PS2, PS3, PS4, PS5)","category":"Jeux Vidéo","difficulty":"easy","fun_fact":"Sans compter les portables PSP et PS Vita"},
    {"id":"jv018","question":"Quel jeu indé vendu à plus de 30 millions a été créé par 2 personnes ?","answer":"Stardew Valley","category":"Jeux Vidéo","difficulty":"hard","fun_fact":"Créé seul par Eric Barone en 4 ans"},
    {"id":"jv019","question":"Quel est le jeu d'Atari le plus iconique ?","answer":"Pong (1972)","category":"Jeux Vidéo","difficulty":"medium","fun_fact":"L'un des premiers jeux vidéo commerciaux"},
    {"id":"jv020","question":"Quel jeu a popularisé le genre rogue-like ?","answer":"Rogue (1980)","category":"Jeux Vidéo","difficulty":"hard","fun_fact":"Inspiré de Donjons & Dragons"},

    # ===== ABSURDE & FUN (25) =====
    {"id":"af001","question":"Quelle est la probabilité d'être frappé par la foudre ?","answer":"1 sur 15 000 dans une vie","category":"Absurde & Fun","difficulty":"hard","fun_fact":"Certaines personnes ont été frappées 7 fois"},
    {"id":"af002","question":"Combien de pizzas mangent les Américains par seconde ?","answer":"Environ 350","category":"Absurde & Fun","difficulty":"hard","fun_fact":"3 milliards par an aux USA"},
    {"id":"af003","question":"Que font 72% des conducteurs en voiture ?","answer":"Chanter","category":"Absurde & Fun","difficulty":"medium","fun_fact":"Devant téléphoner et manger"},
    {"id":"af004","question":"Combien de selfies sont pris par jour dans le monde ?","answer":"Environ 93 millions","category":"Absurde & Fun","difficulty":"hard","fun_fact":"Plus d'un million par seconde aux heures de pointe"},
    {"id":"af005","question":"Quel animal peut survivre sans tête plusieurs semaines ?","answer":"Le cafard","category":"Absurde & Fun","difficulty":"medium","fun_fact":"Il meurt finalement de faim"},
    {"id":"af006","question":"Combien de fois cligne-t-on des yeux par jour ?","answer":"15 000 à 20 000 fois","category":"Absurde & Fun","difficulty":"medium","fun_fact":"On passe ~10% du temps éveillé les yeux fermés"},
    {"id":"af007","question":"Quel est le record du plus long baiser ?","answer":"58 heures 35 minutes","category":"Absurde & Fun","difficulty":"hard","fun_fact":"Record en Thaïlande, 2013"},
    {"id":"af008","question":"Combien de canettes de soda ouvre-t-on dans le monde par seconde ?","answer":"Environ 9000","category":"Absurde & Fun","difficulty":"hard","fun_fact":"Coca-Cola en représente une grande part"},
    {"id":"af009","question":"Quelle est la durée de la vie d'une mouche domestique ?","answer":"Environ 28 jours","category":"Absurde & Fun","difficulty":"medium","fun_fact":"Mais elle peut pondre 500 œufs par cycle"},
    {"id":"af010","question":"Combien de fois va-t-on aux toilettes en moyenne par an ?","answer":"Environ 2500 fois","category":"Absurde & Fun","difficulty":"hard","fun_fact":"Soit 7 fois par jour en moyenne"},
    {"id":"af011","question":"Quel est le record du plus grand château de cartes ?","answer":"7,86 mètres de haut","category":"Absurde & Fun","difficulty":"hard","fun_fact":"Construit en 2007 par Bryan Berg avec 218792 cartes"},
    {"id":"af012","question":"Combien de spaghettis y a-t-il dans 1 kg ?","answer":"Environ 800 spaghettis","category":"Absurde & Fun","difficulty":"hard","fun_fact":"Selon le calibre de la pâte"},
    {"id":"af013","question":"Quelle est la moyenne d'âge pour avoir son premier baiser ?","answer":"Environ 15 ans","category":"Absurde & Fun","difficulty":"medium","fun_fact":"Variable selon les cultures"},
    {"id":"af014","question":"Combien de livres sont publiés chaque année dans le monde ?","answer":"Plus de 2 millions","category":"Absurde & Fun","difficulty":"hard","fun_fact":"Soit environ 4 livres par minute"},
    {"id":"af015","question":"Quel est le sport le plus regardé au monde ?","answer":"Le football","category":"Absurde & Fun","difficulty":"easy","fun_fact":"3,5 milliards de fans"},
    {"id":"af016","question":"Combien de personnes utilisent Internet ?","answer":"Environ 5,5 milliards","category":"Absurde & Fun","difficulty":"medium","fun_fact":"Soit ~67% de la population mondiale"},
    {"id":"af017","question":"Quel est le plat le plus consommé au monde ?","answer":"Le riz","category":"Absurde & Fun","difficulty":"easy","fun_fact":"Aliment de base pour la moitié de l'humanité"},
    {"id":"af018","question":"Combien de morceaux de Lego sont produits chaque seconde ?","answer":"Environ 36000","category":"Absurde & Fun","difficulty":"hard","fun_fact":"Soit plus d'un trillion produits depuis 1949"},
    {"id":"af019","question":"Combien de tasses de café sont bues par jour dans le monde ?","answer":"Environ 2,25 milliards","category":"Absurde & Fun","difficulty":"hard","fun_fact":"Café = deuxième matière la plus échangée après le pétrole"},
    {"id":"af020","question":"Quelle est la chanson la plus écoutée sur Spotify ?","answer":"Blinding Lights (The Weeknd)","category":"Absurde & Fun","difficulty":"medium","fun_fact":"Plus de 4 milliards d'écoutes"},
    {"id":"af021","question":"Combien de mots un humain prononce-t-il par jour en moyenne ?","answer":"Environ 16000 mots","category":"Absurde & Fun","difficulty":"medium","fun_fact":"Selon une étude de l'université d'Arizona"},
    {"id":"af022","question":"Combien de fois pète un humain par jour en moyenne ?","answer":"Environ 14 fois","category":"Absurde & Fun","difficulty":"medium","fun_fact":"Pour un volume total de 0,5 à 2 litres"},
    {"id":"af023","question":"Quelle est la valeur du plus gros billet jamais imprimé ?","answer":"100 000 dollars (USA, 1934)","category":"Absurde & Fun","difficulty":"hard","fun_fact":"Utilisé uniquement entre banques fédérales"},
    {"id":"af024","question":"Combien de paires de chaussures possède une femme en moyenne ?","answer":"Environ 19 paires","category":"Absurde & Fun","difficulty":"medium","fun_fact":"Contre 12 pour les hommes"},
    {"id":"af025","question":"Quelle est la durée du plus long film jamais réalisé ?","answer":"857 heures (Logistics, 2012)","category":"Absurde & Fun","difficulty":"hard","fun_fact":"Soit 35 jours et demi non-stop"},
]
